/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openbravo.pos.sales.restaurant;

import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author shilpa
 */
//Class to show buffer popup
public class JRetailBufferWindow extends javax.swing.JDialog {
    int x = 500;
    int y = 300;
    int width = 350;
    int height = 220;
    /**
     * Creates new form JRetailBufferWindow
     */
    public JRetailBufferWindow(java.awt.Frame frame, boolean modal) {
       super(frame, true);
        setBounds(x, y, width, height);
    }

     private JRetailBufferWindow(Dialog dialog, boolean b) {
        super(dialog, true);
        setBounds(x, y, width, height);

    }
   
     public static void showMessage(Component parent) {
        Window window = getWindow(parent);
        JRetailBufferWindow myMsg;
        if (window instanceof Frame) {
            myMsg = new JRetailBufferWindow((Frame) window, true);
        } else {
            myMsg = new JRetailBufferWindow((Dialog) window, true);
        }
        myMsg.loadContent();
    }
    
      public  void loadContent() {
        initComponents();
        RefreshTickets autoRefresh = new RefreshTickets();
        //timer to show popup for only 1 sec
            Timer timer = new Timer(1000, autoRefresh);
            //dont repeat th timer
           timer.setRepeats(false);
           timer.start();
           setVisible(true);
      }
      
      private static Window getWindow(Component parent) {
        if (parent == null) {
            return new JFrame();
        } else if (parent instanceof Frame || parent instanceof Dialog) {
            return (Window) parent;
        } else {
            return getWindow(parent.getParent());
        }
    }
      
        

   
      
       private class RefreshTickets implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            System.out.println("inside refresh");
           setVisible(false);
           dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/loading.gif"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 161, 58));
        jLabel2.setText(" The table is being accessed by another User!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
