/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openbravo.pos.inventory;

import com.openbravo.basic.BasicException;
import com.openbravo.pos.customers.DataLogicCustomers;
import com.openbravo.pos.forms.AppView;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.Window;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JScrollPane;

/**
 *
 * @author sysfore17
 */
public class JDialogRoles extends JDialog {
    int x = 530;
    int y = 270;
    int width = 320;
    int height = 50;
    private java.util.List<RoleInfo> rolesList;
    private java.util.List<String> selectedList;
    public static boolean isclose=false;
     JCheckBox[] checkBoxList=null;
    /**
     * Creates new form JDialogRoles
     */
    public JDialogRoles(Frame frame, boolean b) {
         super(frame, b);
        setBounds(x, y, width, height);
    }
    
    public static java.util.List<String> showMessage(Component parent, DataLogicCustomers dlSales,AppView app,java.util.List<String> oldKodRolelist) {

        Window window = getWindow(parent);
        JDialogRoles myMsg;
        if (window instanceof Frame) {
            myMsg = new JDialogRoles((Frame) window, true);
        } else {
            myMsg = new JDialogRoles((Dialog) window, true);
        }
         
       return myMsg.init(dlSales, app,oldKodRolelist);

    }

    private JDialogRoles(Dialog dialog, boolean b) {
        super(dialog, b);
        setBounds(x, y, width, height);
        //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jPanelRole = new javax.swing.JPanel();
        jPanelButtons = new javax.swing.JPanel();
        okay = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelRole.setAutoscrolls(true);
        jPanelRole.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane.setViewportView(jPanelRole);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        jPanelButtons.setPreferredSize(new java.awt.Dimension(100, 40));

        okay.setText("Ok");
        okay.setPreferredSize(new java.awt.Dimension(60, 30));
        okay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okayActionPerformed(evt);
            }
        });
        jPanelButtons.add(okay);

        jButtonCancel.setText("Cancel");
        jButtonCancel.setAlignmentX(2.0F);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonCancel);

        getContentPane().add(jPanelButtons, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okayActionPerformed
        isclose=false;
        for(Component component : jPanelRole.getComponents()) {
            if(component instanceof JCheckBox){
                if(((JCheckBox)component).isSelected()){
                    javax.swing.JCheckBox  m_jChkRoleName= (JCheckBox)component;
                    selectedList.add(m_jChkRoleName.getActionCommand());
                }
            }
        }
        System.out.println("after saying okay"+selectedList.size());
        dispose();
    }//GEN-LAST:event_okayActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        isclose=true;
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

       private static Window getWindow(Component parent) {
        if (parent == null) {
            return new JFrame();
        } else if (parent instanceof Frame || parent instanceof Dialog) {
            return (Window) parent;
        } else {
            return getWindow(parent.getParent());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelRole;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton okay;
    // End of variables declaration//GEN-END:variables

    private java.util.List<String>  init(DataLogicCustomers dlcustomers, AppView app,java.util.List<String> oldKodRolelist) {
        try {
            initComponents();
            this.setResizable(false);
            jPanelRole.setLayout(new GridLayout(0, 2, 3, 0));
            this.setSize(300, 200);
            this.setResizable(false);
            rolesList = dlcustomers.getRolesList();
            selectedList=new ArrayList();
            int numberCheckBox = rolesList.size();
            checkBoxList = new JCheckBox[numberCheckBox];
            int dimension=40;
           //Dynamically adding checkboxes based on number of roles (By Shilpa)
           for (int i = 0; i < numberCheckBox; i++) {
            javax.swing.JCheckBox  m_jChkRoleName= new javax.swing.JCheckBox();    
            m_jChkRoleName.setLabel(rolesList.get(i).getName());
            //assigning each checkbox a unique Id(Role Id) 
            m_jChkRoleName.setActionCommand(rolesList.get(i).getId());
            jPanelRole.add(m_jChkRoleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, dimension, -1, -1));
            dimension=dimension+40;  
             //setting checkbox(Role) value based on its presence in KOD  
            if(oldKodRolelist!=null){
              if(oldKodRolelist.contains(rolesList.get(i).getId())){
                m_jChkRoleName.setSelected(true);
                }
              }
           }
          } catch (BasicException ex) {
            Logger.getLogger(JDialogRoles.class.getName()).log(Level.SEVERE, null, ex);
        }
        setTitle("Roles");
        // m_ReturnProduct = null;
         setVisible(true);
          return selectedList;
    }
}
