/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CurrencyLink1.java
 *
 * Created on Mar 6, 2012, 5:14:44 PM
 */
package com.sysfore.pos.cashmanagement;

import com.openbravo.basic.BasicException;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.JPanelView;
import com.sysfore.pos.purchaseorder.PurchaseOrderReceipts;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author mateen
 */

public class CurrencyLink extends javax.swing.JPanel implements JPanelView {

    private AppView app;
    private CurrencyConfigLoader currLoad;
    private int rows;
    private TableModel model;
    private CurrencyTableListener currencyListener;
    private PurchaseOrderReceipts m_dlPOReceipts;

    /** Creates new form CurrencyLink1 */
    public CurrencyLink(AppView app) {

        this.app = app;
        this.m_dlPOReceipts = (PurchaseOrderReceipts) app.getBean("com.sysfore.pos.purchaseorder.PurchaseOrderReceipts");
        initComponents();
        List<CurrencyInfo> info = initLocaleSpecificData();
        if (info.size() > 0) {
            String[] currencyList = info.get(0).getDenominations().split(",");
            setRows(currencyList.length);
            Object[] obj = {"Denomination", "Count", "Total"};
            jTable1.setModel(new DefaultTableModel(obj, getRows()));

            jTable1.setRowHeight(30);
            populateJtable(currencyList);
            currencyListener = new CurrencyTableListener(jTable1, currencyList);
            jTable1.getModel().addTableModelListener(currencyListener);
        }else{
            jLblDenominations.setText("Currency not available for country " + Locale.getDefault().getCountry());
        }
    }

    private void populateJtable(String[] currencyList) {
        model = jTable1.getModel();
        for (int r = 0; r < getRows(); r++) {
            model.setValueAt(currencyList[r], r, 0);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTxtTotal = new javax.swing.JTextField();
        jBtnReconcile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLblDenominations = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new DefaultTableModel());
        jScrollPane1.setViewportView(jTable1);

        jTxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTotalActionPerformed(evt);
            }
        });

        jBtnReconcile.setText("Cash Reconcile");
        jBtnReconcile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReconcileActionPerformed(evt);
            }
        });

        jLabel1.setText("Total");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Total Sales Collection:");

        jLabel3.setText("Float Amount:");

        jLabel4.setText("Total Amount Collection:");

        jLabel6.setText("Tender Breakup:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLblDenominations, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLblDenominations, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jBtnReconcile, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)
                            .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnReconcile, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTotalActionPerformed

    private void jBtnReconcileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReconcileActionPerformed
        // TODO add your handling code here:
        jBtnReconcileAction();
    }//GEN-LAST:event_jBtnReconcileActionPerformed

    public String getTitle() {
        return AppLocal.getIntString("CD.Menu");
    }

    public void activate() throws BasicException {
    }

    public boolean deactivate() {
        return true;
    }

    public JComponent getComponent() {
        return this;
    }

    private List<CurrencyInfo> initLocaleSpecificData() {
        jLblDenominations.setText("Currency " + Locale.getDefault().getCountry());
        currLoad = new CurrencyConfigLoader(Locale.getDefault().getCountry(), null, app);
        java.util.List<CurrencyInfo> list = null;
        try {
            list = currLoad.loadCurrencyArray();
        } catch (BasicException ex) {
            Logger.getLogger(CurrencyLink.class.getName()).log(Level.SEVERE, null, ex);
        }
        return list;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnReconcile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblDenominations;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables

    private int getRows() {
        return rows;
    }

    private void setRows(int rows) {
        this.rows = rows;
    }

    private void jBtnReconcileAction() {
        jTable1.changeSelection(1, 3, false, false);
        List<DenominationTable> dTable = new ArrayList<DenominationTable>();
        double sum = 0;
        double subTotal = 0;
        for (int r = 0; r < getRows(); r++) {
            double value = Double.parseDouble(jTable1.getValueAt(r, 0).toString());
            String strCount = jTable1.getValueAt(r, 1).toString();
            if(strCount.isEmpty() || strCount.equals(null)){
                strCount = "0";
            }
            int count = Integer.parseInt(strCount);
            subTotal = value * count;
            jTable1.setValueAt(subTotal, r, 2);
            sum += subTotal;
            dTable.add(new DenominationTable(value, count, subTotal));
        }
        jTxtTotal.setText(sum + "");
        //try {
         //   m_dlPOReceipts.insertReconciliation(dTable, sum);
       // } catch (BasicException ex) {
       //     Logger.getLogger(CurrencyLink.class.getName()).log(Level.SEVERE, null, ex);
      //  }
    }
}
