//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2007-2009 Openbravo, S.L.
//    http://www.openbravo.com/product/pos
//
//    This file is part of Openbravo POS.
//
//    Openbravo POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Openbravo POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.ticket;

import com.openbravo.data.loader.SerializerWrite;
import com.openbravo.pos.forms.AppLocal;

import com.openbravo.pos.forms.AppView;
import java.awt.Component;
import java.util.List;
import com.openbravo.data.loader.QBFCompareEnum;
import com.openbravo.format.Formats;
import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.ListQBFModelNumber;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.SentenceList;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.reports.ReportEditorCreator;
import com.sysfore.pos.creditsale.JCreditSales;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class CustomerMandotaryFilter extends javax.swing.JPanel implements ReportEditorCreator {
    
    private SentenceList m_sentcat;
    private ComboBoxValModel m_CategoryModel;

    /** Creates new form JQBFProduct */
    public CustomerMandotaryFilter() {

        initComponents();
    }
    
    public void init(AppView app) {
         
        DataLogicSales dlSales = (DataLogicSales) app.getBean("com.openbravo.pos.forms.DataLogicSales");
       
        // El modelo de categorias
        m_sentcat = dlSales.getCustomerNameList();
        m_CategoryModel = new ComboBoxValModel();          
     
        //m_jCboName.setModel(new ListQBFModelNumber());
        //m_jCboPriceBuy.setModel(new ListQBFModelNumber());
        //m_jCboPriceSell.setModel(new ListQBFModelNumber());
    }
    
    public void activate() throws BasicException {

        List catlist = m_sentcat.list();
        catlist.add(0, null);
        m_CategoryModel = new ComboBoxValModel(catlist);
        m_jCustomer.setModel(m_CategoryModel);
    }
    
    public SerializerWrite getSerializerWrite() {
        return new SerializerWriteBasic(
                new Datas[] {Datas.OBJECT, Datas.STRING});
    }

    public Component getComponent() {
        return this;
    }
   
  //  public Object createValue() throws BasicException {
//        
//        if (m_jBarcode.getText() == null || m_jBarcode.getText().equals("")) {
//            // Filtro por formulario
//            return new Object[] {
//                 m_CategoryModel.getSelectedKey() == null ? QBFCompareEnum.COMP_NONE : QBFCompareEnum.COMP_EQUALS, m_CategoryModel.getSelectedKey(),
//                QBFCompareEnum.COMP_NONE, null         
//            };
//        } else {            
//            // Filtro por codigo de barras.
//            return new Object[] {
//              
//                QBFCompareEnum.COMP_RE, "%" + m_jBarcode.getText() + "%"
//            };
//        }
  //  } 
// 
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_jCustomer = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(514, 32));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        m_jCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jCustomerActionPerformed(evt);
            }
        });
        add(m_jCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3, 200, 20));

        jLabel2.setText("Customer ");
        jLabel2.setPreferredSize(new java.awt.Dimension(110, 14));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 3, 107, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void m_jCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_jCustomerActionPerformed
   
      private JPanel getLabelRedPanel(String msg) {
    JPanel panel = new JPanel();
    Font font = new Font("Verdana", Font.BOLD, 12);
    panel.setFont(font);
    panel.setOpaque(true);
  //  panel.setBackground(Color.BLUE);
    JLabel helloLabel = new JLabel(msg, JLabel.LEFT);
    helloLabel.setForeground(Color.red);
    helloLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    panel.add(helloLabel);

    return panel;
}
 private void showMsg(CustomerMandotaryFilter aThis, String msg) {
       JOptionPane.showMessageDialog(aThis,getLabelRedPanel(msg),"Message",
                JOptionPane.INFORMATION_MESSAGE);
     }
    
////    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox m_jCustomer;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object createValue() throws BasicException {
      //  if(m_CategoryModel.getSelectedKey() == null)
        //{
     // showMsg(this,"Please Select The Customer");
      //return null;
        //}
       // else{
          return new Object[] {
            //    m_jCboName.getSelectedItem(), m_jName.getText(),
            //    m_jCboPriceBuy.getSelectedItem(), Formats.CURRENCY.parseValue(m_jPriceBuy.getText()),           
           //     m_jCboPriceSell.getSelectedItem(), Formats.CURRENCY.parseValue(m_jPriceSell.getText()),
                m_CategoryModel.getSelectedKey() == null ? QBFCompareEnum.COMP_NONE : QBFCompareEnum.COMP_EQUALS, m_CategoryModel.getSelectedKey(),
                QBFCompareEnum.COMP_NONE, null         
            };
       
  //  }
    }
    }
  //  }      

