--    Openbravo POS is a point of sales application designed for touch screens.
--    Copyright (C) 2007-2009 Openbravo, S.L.
--    http://sourceforge.net/projects/openbravopos
--
--    This file is part of Openbravo POS.
--
--    Openbravo POS is free software: you can redistribute it and/or modify
--    it under the terms of the GNU General Public License as published by
--    the Free Software Foundation, either version 3 of the License, or
--    (at your option) any later version.
--
--    Openbravo POS is distributed in the hope that it will be useful,
--    but WITHOUT ANY WARRANTY; without even the implied warranty of
--    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--    GNU General Public License for more details.
--
--    You should have received a copy of the GNU General Public License
--    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

-- Database initial script for MYSQL
-- v2.30

CREATE TABLE APPLICATIONS (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    VERSION VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--INSERT INTO APPLICATIONS(ID, NAME, VERSION) VALUES($APP_ID{}, $APP_NAME{}, $APP_VERSION{});

CREATE TABLE ROLES (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PERMISSIONS MEDIUMBLOB,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX ROLES_NAME_INX ON ROLES(NAME);
--INSERT INTO ROLES(ID, NAME, PERMISSIONS) VALUES('0', 'Admin', $FILE{/com/openbravo/pos/templates/Role.Administrator.xml} );
--INSERT INTO ROLES(ID, NAME, PERMISSIONS) VALUES('1', 'Cashier', $FILE{/com/openbravo/pos/templates/Role.Cashier.xml} );
--INSERT INTO ROLES(ID, NAME, PERMISSIONS) VALUES('2', 'Superadmin', $FILE{/com/openbravo/pos/templates/Role.Syscashier.xml} );
--INSERT INTO ROLES(ID, NAME, PERMISSIONS) VALUES('1', 'Manager role', $FILE{/com/openbravo/pos/templates/Role.Manager.xml} );
--INSERT INTO ROLES(ID, NAME, PERMISSIONS) VALUES('2', 'Employee role', $FILE{/com/openbravo/pos/templates/Role.Employee.xml} );
--INSERT INTO ROLES(ID, NAME, PERMISSIONS) VALUES('3', 'Guest role', $FILE{/com/openbravo/pos/templates/Role.Guest.xml} );

CREATE TABLE POSDETAILS (
    ID INTEGER NOT NULL,
    POSNO INTEGER NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--INSERT INTO POSDETAILS(ID, POSNO) VALUES(1, 1 );
--INSERT INTO POSDETAILS(ID, POSNO) VALUES(2, 2 );
--INSERT INTO POSDETAILS(ID, POSNO) VALUES(3, 3 );
--INSERT INTO POSDETAILS(ID, POSNO) VALUES(4, 4 );

CREATE TABLE PEOPLE (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    APPPASSWORD VARCHAR(255),
    CARD VARCHAR(255),
    ROLE VARCHAR(255) NOT NULL,
    VISIBLE BIT NOT NULL,
    IMAGE MEDIUMBLOB,
    ISDELIVERYBOY VARCHAR(255) DEFAULT 'N',
    ACCESS int(11) NOT NULL DEFAULT '0',
    PRIMARY KEY (ID),
    CONSTRAINT PEOPLE_FK_1 FOREIGN KEY (ROLE) REFERENCES ROLES(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX PEOPLE_NAME_INX ON PEOPLE(NAME);
CREATE INDEX PEOPLE_CARD_INX ON PEOPLE(CARD);

--INSERT INTO PEOPLE(ID, NAME, APPPASSWORD, ROLE, VISIBLE, IMAGE) VALUES ('0', 'admin', 'admin', '0', TRUE, NULL);
--INSERT INTO PEOPLE(ID, NAME, APPPASSWORD, ROLE, VISIBLE, IMAGE) VALUES ('1', 'cashier', 'cashier', '1', TRUE, NULL);
--INSERT INTO PEOPLE(ID, NAME, APPPASSWORD, ROLE, VISIBLE, IMAGE) VALUES ('2', 'superadmin', 'superadmin', '2', TRUE, NULL);
--INSERT INTO PEOPLE(ID, NAME, APPPASSWORD, ROLE, VISIBLE, IMAGE) VALUES ('3', 'Guest', NULL, '3', TRUE, NULL);

CREATE TABLE RESOURCES (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    RESTYPE INTEGER NOT NULL,
    CONTENT MEDIUMBLOB,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX RESOURCES_NAME_INX ON RESOURCES(NAME);
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('0', 'Printer.Start', 0, $FILE{/com/openbravo/pos/templates/Printer.Start.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('1', 'Printer.Ticket', 0, $FILE{/com/openbravo/pos/templates/Printer.Ticket.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('2', 'Printer.Ticket2', 0, $FILE{/com/openbravo/pos/templates/Printer.Ticket2.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('3', 'Printer.TicketPreview', 0, $FILE{/com/openbravo/pos/templates/Printer.TicketPreview.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('4', 'Printer.TicketTotal', 0, $FILE{/com/openbravo/pos/templates/Printer.TicketTotal.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('5', 'Printer.OpenDrawer', 0, $FILE{/com/openbravo/pos/templates/Printer.OpenDrawer.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('6', 'Printer.Ticket.Logo', 1, $FILE{/com/openbravo/pos/templates/Printer.Ticket.Logo.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('7', 'Printer.TicketLine', 0, $FILE{/com/openbravo/pos/templates/Printer.TicketLine.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('8', 'Printer.CloseCash', 0, $FILE{/com/openbravo/pos/templates/Printer.CloseCash.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('9', 'Window.Logo', 1, $FILE{/com/openbravo/pos/templates/Window.Logo.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('10', 'Window.Title', 0, $FILE{/com/openbravo/pos/templates/Window.Title.txt});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('11', 'Ticket.Buttons', 0, $FILE{/com/openbravo/pos/templates/Ticket.Buttons.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('12', 'Ticket.Line', 0, $FILE{/com/openbravo/pos/templates/Ticket.Line.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('13', 'Printer.Inventory', 0, $FILE{/com/openbravo/pos/templates/Printer.Inventory.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('14', 'Menu.Root', 0, $FILE{/com/openbravo/pos/templates/Menu.Root.txt});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('15', 'Printer.CustomerPaid', 0, $FILE{/com/openbravo/pos/templates/Printer.CustomerPaid.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('16', 'Printer.CustomerPaid2', 0, $FILE{/com/openbravo/pos/templates/Printer.CustomerPaid2.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('17', 'payment.cash', 0, $FILE{/com/openbravo/pos/templates/payment.cash.txt});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('18', 'banknote.50euro', 1, $FILE{/com/openbravo/pos/templates/banknote.50euro.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('19', 'banknote.20euro', 1, $FILE{/com/openbravo/pos/templates/banknote.20euro.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('20', 'banknote.10euro', 1, $FILE{/com/openbravo/pos/templates/banknote.10euro.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('21', 'banknote.5euro', 1, $FILE{/com/openbravo/pos/templates/banknote.5euro.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('22', 'coin.2euro', 1, $FILE{/com/openbravo/pos/templates/coin.2euro.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('23', 'coin.1euro', 1, $FILE{/com/openbravo/pos/templates/coin.1euro.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('24', 'coin.50cent', 1, $FILE{/com/openbravo/pos/templates/coin.50cent.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('25', 'coin.20cent', 1, $FILE{/com/openbravo/pos/templates/coin.20cent.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('26', 'coin.10cent', 1, $FILE{/com/openbravo/pos/templates/coin.10cent.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('27', 'coin.5cent', 1, $FILE{/com/openbravo/pos/templates/coin.5cent.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('28', 'coin.2cent', 1, $FILE{/com/openbravo/pos/templates/coin.2cent.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('29', 'coin.1cent', 1, $FILE{/com/openbravo/pos/templates/coin.1cent.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('30', 'Printer.PartialCash', 0, $FILE{/com/openbravo/pos/templates/Printer.PartialCash.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('31', 'Printer.CloseShift', 0, $FILE{/com/openbravo/pos/templates/Printer.CloseShift.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('32', 'Printer.CloseDay', 0, $FILE{/com/openbravo/pos/templates/Printer.CloseDay.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('33', 'Printer.CreditNote', 0, $FILE{/com/openbravo/pos/templates/Printer.CreditNote.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('34', 'Printer.DuplicateCreditNote', 0, $FILE{/com/openbravo/pos/templates/Printer.DuplicateCreditNote.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('35', 'code.ReceiptConsolidate', 0, $FILE{/com/openbravo/pos/templates/code.ReceiptConsolidate.txt});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('36', 'Printer.BankDeposit', 0, $FILE{/com/openbravo/pos/templates/Printer.BankDeposit.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('37', 'Printer.DuplicateBill', 0, $FILE{/com/openbravo/pos/templates/Printer.DuplicateBill.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('38', 'Printer.PurchaseOrder', 0, $FILE{/com/openbravo/pos/templates/Printer.PurchaseOrder.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('39', 'Printer.Bill', 0, $FILE{/com/openbravo/pos/templates/Printer.Bill.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('40', 'Printer.HomeDelivery', 0, $FILE{/com/openbravo/pos/templates/Printer.HomeDelivery.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('41', 'Printer.Kot', 0, $FILE{/com/openbravo/pos/templates/Printer.Kot.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('42', 'Printer.NonChargableBill', 0, $FILE{/com/openbravo/pos/templates/Printer.NonChargableBill.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('43', 'Printer.DuplicateHomeDelivery', 0, $FILE{/com/openbravo/pos/templates/Printer.DuplicateHomeDelivery.xml});

CREATE TABLE TAXCUSTCATEGORIES (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX TAXCUSTCAT_NAME_INX ON TAXCUSTCATEGORIES(NAME);

CREATE TABLE CUSTOMERS (
    ID VARCHAR(255) NOT NULL,
    SEARCHKEY VARCHAR(40) NOT NULL,
    TAXID VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    TAXCATEGORY VARCHAR(255),
    CARD VARCHAR(255),
    MAXDEBT DOUBLE DEFAULT 0 NOT NULL,
    ADDRESS VARCHAR(255),
    ADDRESS2 VARCHAR(255),
    ISADDRESS1BILLADDRESS BIT DEFAULT b'0' NOT NULL,
    ISADDRESS2SHIFTADDRESS BIT DEFAULT b'0' NOT NULL,
    CUSTOMERID VARCHAR(40),
    POSTAL VARCHAR(255),
    CITY VARCHAR(255),
    REGION VARCHAR(255),
    COUNTRY VARCHAR(255),
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(255),
    PHONE2 VARCHAR(255),
    FAX VARCHAR(255),
    NOTES VARCHAR(255),
    VISIBLE BIT DEFAULT b'1' NOT NULL,
    CURDATE DATETIME,
    CURDEBT DOUBLE,
    ISCUSTOMER BIT DEFAULT b'0' NOT NULL,
    BILLADDRESS varchar(1000) DEFAULT NULL,
    SHIFTADDRESS varchar(1000) DEFAULT NULL,
    ISCREDITCUSTOMER BIT DEFAULT b'0' NOT NULL,
    ISPOSCUSTOMER VARCHAR(1) DEFAULT 'Y',
    CUSTOMERRECEIVABLE VARCHAR(60),
    CUSTOMERADVANCE VARCHAR(60),
    PRIMARY KEY (ID),
    CONSTRAINT CUSTOMERS_TAXCAT FOREIGN KEY (TAXCATEGORY) REFERENCES TAXCUSTCATEGORIES(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX CUSTOMERS_SKEY_INX ON CUSTOMERS(SEARCHKEY);
CREATE INDEX CUSTOMERS_TAXID_INX ON CUSTOMERS(TAXID);
CREATE INDEX CUSTOMERS_NAME_INX ON CUSTOMERS(NAME);
CREATE INDEX CUSTOMERS_CARD_INX ON CUSTOMERS(CARD);

CREATE TABLE UOM (
  ID varchar(255) NOT NULL,
  CODE varchar(255) NOT NULL,
  NAME varchar(255) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CATEGORIES (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PARENTID VARCHAR(255),
    IMAGE MEDIUMBLOB,
    PRIMARY KEY(ID),
    CONSTRAINT CATEGORIES_FK_1 FOREIGN KEY (PARENTID) REFERENCES CATEGORIES(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX CATEGORIES_NAME_INX ON CATEGORIES(NAME);
--INSERT INTO CATEGORIES(ID, NAME) VALUES ('000', 'Category Standard');

CREATE TABLE TAXCATEGORIES (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX TAXCAT_NAME_INX ON TAXCATEGORIES(NAME);
--INSERT INTO TAXCATEGORIES(ID, NAME) VALUES ('000', 'Tax Exempt');
--INSERT INTO TAXCATEGORIES(ID, NAME) VALUES ('001', 'Tax Standard');

CREATE TABLE TAXES (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    CUSTCATEGORY VARCHAR(255),
    PARENTID VARCHAR(255),
    RATE DOUBLE NOT NULL,
 VALIDFROM timestamp NOT NULL,
  ISSUMMARY varchar(1) NOT NULL DEFAULT 'N',
BASEAMOUNT varchar(60) NOT NULL DEFAULT 'LNA',
TAXBASEID varchar(32) ,
DOCTAXAMOUNT varchar(60) NOT NULL DEFAULT 'D',
ISSERVICECHARGE VARCHAR(1) NOT NULL DEFAULT 'N',
 RATECASCADE BIT DEFAULT b'0' NOT NULL,
   RATEORDER INTEGER,
    ISSALESTAX VARCHAR(1) NOT NULL DEFAULT 'N',
    ISPURCHASETAX VARCHAR(1) NOT NULL DEFAULT 'N',
    ISSERVICETAX VARCHAR(1) NOT NULL DEFAULT 'N',
    DEBITACCOUNT VARCHAR(60) DEFAULT NULL,
    CREDITACCOUNT VARCHAR(60) DEFAULT NULL,
     ISTAKEAWAY varchar(1) NOT NULL DEFAULT 'N',
    PRIMARY KEY(ID),
    CONSTRAINT TAXES_CAT_FK FOREIGN KEY (CATEGORY) REFERENCES TAXCATEGORIES(ID),
    CONSTRAINT TAXES_CUSTCAT_FK FOREIGN KEY (CUSTCATEGORY) REFERENCES TAXCUSTCATEGORIES(ID),
    CONSTRAINT TAXES_TAXES_FK FOREIGN KEY (PARENTID) REFERENCES TAXES(ID),
    CONSTRAINT tax_taxbase FOREIGN KEY (TAXBASEID)
REFERENCES TAXES (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX TAXES_NAME_INX ON TAXES(NAME);
--INSERT INTO TAXES(ID, NAME, CATEGORY, CUSTCATEGORY, PARENTID, RATE, RATECASCADE, RATEORDER) VALUES ('000', 'Tax Exempt', '000', NULL, NULL, 0, FALSE, NULL);
--INSERT INTO TAXES(ID, NAME, CATEGORY, CUSTCATEGORY, PARENTID, RATE, RATECASCADE, RATEORDER) VALUES ('001', 'Tax Standard', '001', NULL, NULL, 0.10, FALSE, NULL);

CREATE TABLE ATTRIBUTE (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ATTRIBUTEVALUE (
    ID VARCHAR(255) NOT NULL,
    ATTRIBUTE_ID VARCHAR(255) NOT NULL,
    VALUE VARCHAR(255),
    PRIMARY KEY (ID),
    CONSTRAINT ATTVAL_ATT FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ATTRIBUTE(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ATTRIBUTESET (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ATTRIBUTEUSE (
    ID VARCHAR(255) NOT NULL,
    ATTRIBUTESET_ID VARCHAR(255) NOT NULL,
    ATTRIBUTE_ID VARCHAR(255) NOT NULL,
    LINENO INTEGER,
    PRIMARY KEY (ID),
    CONSTRAINT ATTUSE_SET FOREIGN KEY (ATTRIBUTESET_ID) REFERENCES ATTRIBUTESET(ID) ON DELETE CASCADE,
    CONSTRAINT ATTUSE_ATT FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ATTRIBUTE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX ATTUSE_LINE ON ATTRIBUTEUSE(ATTRIBUTESET_ID, LINENO);

CREATE TABLE ATTRIBUTESETINSTANCE (
    ID VARCHAR(255) NOT NULL,
    ATTRIBUTESET_ID VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRIMARY KEY (ID),
    CONSTRAINT ATTSETINST_SET FOREIGN KEY (ATTRIBUTESET_ID) REFERENCES ATTRIBUTESET(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ATTRIBUTEINSTANCE (
    ID VARCHAR(255) NOT NULL,
    ATTRIBUTESETINSTANCE_ID VARCHAR(255) NOT NULL,
    ATTRIBUTE_ID VARCHAR(255) NOT NULL,
    VALUE VARCHAR(255),
    PRIMARY KEY (ID),
    CONSTRAINT ATTINST_SET FOREIGN KEY (ATTRIBUTESETINSTANCE_ID) REFERENCES ATTRIBUTESETINSTANCE(ID) ON DELETE CASCADE,
    CONSTRAINT ATTINST_ATT FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ATTRIBUTE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PRODUCTS (
    ID VARCHAR(255) NOT NULL,
    REFERENCE VARCHAR(255) NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    CODETYPE VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    PRICEBUY DOUBLE NOT NULL,
    PRICESELL DOUBLE NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    TAXCAT VARCHAR(255) NOT NULL,
    ATTRIBUTESET_ID VARCHAR(255),
    STOCKCOST DOUBLE,
    STOCKVOLUME DOUBLE,
    IMAGE MEDIUMBLOB,
    ISCOM BIT DEFAULT b'0' NOT NULL,
    ISSCALE BIT DEFAULT b'0' NOT NULL,
    ATTRIBUTES MEDIUMBLOB,
    ITEMCODE VARCHAR(255) NOT NULL,
    MRP DOUBLE NOT NULL,
    ISACTIVE VARCHAR(1) DEFAULT 'Y',
    ISSALESITEM VARCHAR(1) DEFAULT 'N',
    ISPURCHASEITEM VARCHAR(1) DEFAULT 'N',
    UOM VARCHAR(255) NOT NULL,
    POPULAR varchar(1) NOT NULL DEFAULT 'N',
    PRODUCTTYPE varchar(20) DEFAULT NULL,
    PRODUCTIONAREATYPE varchar(32) NOT NULL,
    ISADDON varchar(1) DEFAULT 'N',
    MANDATORYADDON varchar(1) DEFAULT 'N',  
     PREPARATIONTIME TIME DEFAULT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT PRODUCTS_FK_1 FOREIGN KEY (CATEGORY) REFERENCES CATEGORIES(ID),
    CONSTRAINT PRODUCTS_TAXCAT_FK FOREIGN KEY (TAXCAT) REFERENCES TAXCATEGORIES(ID),
    CONSTRAINT PRODUCTS_ATTRSET_FK FOREIGN KEY (ATTRIBUTESET_ID) REFERENCES ATTRIBUTESET(ID),
    CONSTRAINT PRODUCTS_UOM_FK FOREIGN KEY (UOM) REFERENCES UOM(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX PRODUCTS_INX_0 ON PRODUCTS(REFERENCE);
CREATE UNIQUE INDEX PRODUCTS_INX_1 ON PRODUCTS(CODE);
CREATE UNIQUE INDEX PRODUCTS_NAME_INX ON PRODUCTS(NAME);

CREATE TABLE PRODUCTS_CAT (
    PRODUCT VARCHAR(255) NOT NULL,
    CATORDER INTEGER,
    PRIMARY KEY (PRODUCT),
    CONSTRAINT PRODUCTS_CAT_FK_1 FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX PRODUCTS_CAT_INX_1 ON PRODUCTS_CAT(CATORDER);

CREATE TABLE PRODUCTS_COM (
    ID VARCHAR(255) NOT NULL,
    PRODUCT VARCHAR(255) NOT NULL,
    PRODUCT2 VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT PRODUCTS_COM_FK_1 FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID),
    CONSTRAINT PRODUCTS_COM_FK_2 FOREIGN KEY (PRODUCT2) REFERENCES PRODUCTS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX PCOM_INX_PROD ON PRODUCTS_COM(PRODUCT, PRODUCT2);

CREATE TABLE LOCATIONS (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX LOCATIONS_NAME_INX ON LOCATIONS(NAME);
--INSERT INTO LOCATIONS(ID, NAME,ADDRESS) VALUES('0', 'General', NULL);

CREATE TABLE BUSINESSTYPE (
  ID VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  ISHOMEDELIVERY VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (ID),
  UNIQUE KEY businesstype_INX (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--INSERT INTO BUSINESSTYPE(ID, NAME, ISHOMEDELIVERY) VALUES ('1', 'Order Taking', 'N');
--INSERT INTO BUSINESSTYPE(ID, NAME, ISHOMEDELIVERY) VALUES ('2', 'Take Away', 'N');
--INSERT INTO BUSINESSTYPE(ID, NAME, ISHOMEDELIVERY) VALUES ('3', 'Home Delivery', 'N');


CREATE TABLE STOCKDIARY (
    ID VARCHAR(255) NOT NULL,
    DATENEW DATETIME NOT NULL,
    REASON INTEGER NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    PRODUCT VARCHAR(255) NOT NULL,
    ATTRIBUTESETINSTANCE_ID VARCHAR(255),
    UNITS DOUBLE(6,2) DEFAULT '0.0',
    PENDINGQUANTITY double(6,2) DEFAULT '0.0',
    RECEIVINGQUANTITY DOUBLE(6,2) DEFAULT '0.0',
    PRICE DOUBLE NOT NULL,
    POID VARCHAR(255) DEFAULT NULL,
    TPNO VARCHAR(255) DEFAULT NULL,
    TPDATE DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT STOCKDIARY_FK_1 FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID),
    CONSTRAINT STOCKDIARY_ATTSETINST FOREIGN KEY (ATTRIBUTESETINSTANCE_ID) REFERENCES ATTRIBUTESETINSTANCE(ID),
    CONSTRAINT STOCKDIARY_FK_2 FOREIGN KEY (LOCATION) REFERENCES LOCATIONS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX STOCKDIARY_INX_1 ON STOCKDIARY(DATENEW);

CREATE TABLE STOCKLEVEL (
    ID VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    PRODUCT VARCHAR(255) NOT NULL,
    STOCKSECURITY DOUBLE,
    STOCKMAXIMUM DOUBLE,
    PRIMARY KEY (ID),
    CONSTRAINT STOCKLEVEL_PRODUCT FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID),
    CONSTRAINT STOCKLEVEL_LOCATION FOREIGN KEY (LOCATION) REFERENCES LOCATIONS(ID)
 )ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE STOCKCURRENT (
    LOCATION VARCHAR(255) NOT NULL,
    PRODUCT VARCHAR(255) NOT NULL,
    ATTRIBUTESETINSTANCE_ID VARCHAR(255),
    UNITS DOUBLE NOT NULL,
    CONSTRAINT STOCKCURRENT_FK_1 FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID),
    CONSTRAINT STOCKCURRENT_ATTSETINST FOREIGN KEY (ATTRIBUTESETINSTANCE_ID) REFERENCES ATTRIBUTESETINSTANCE(ID),
    CONSTRAINT STOCKCURRENT_FK_2 FOREIGN KEY (LOCATION) REFERENCES LOCATIONS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX STOCKCURRENT_INX ON STOCKCURRENT(LOCATION, PRODUCT, ATTRIBUTESETINSTANCE_ID);

CREATE TABLE CLOSEDCASH (
    MONEY VARCHAR(255) NOT NULL,
    HOST VARCHAR(255) NOT NULL,
    HOSTSEQUENCE INTEGER NOT NULL,
    POSNO VARCHAR(6) NOT NULL,
    DATESTART DATETIME NOT NULL,
    DATEEND DATETIME,
    PRIMARY KEY(MONEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX CLOSEDCASH_INX_1 ON CLOSEDCASH(DATESTART);
CREATE UNIQUE INDEX CLOSEDCASH_INX_SEQ ON CLOSEDCASH(HOST, HOSTSEQUENCE);


CREATE TABLE CLOSEDDAY (
    MONEY VARCHAR(255) NOT NULL,
    HOST VARCHAR(255) NOT NULL,
    HOSTSEQUENCE INTEGER NOT NULL,
    POSNO VARCHAR(6) NOT NULL,
    DATESTART DATETIME NOT NULL,
    DATEEND DATETIME,
    PRIMARY KEY(MONEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX CLOSEDDAYINX_1 ON CLOSEDDAY(DATESTART);
CREATE UNIQUE INDEX CLOSEDDAY_INX_SEQ ON CLOSEDDAY(HOST, HOSTSEQUENCE);

CREATE TABLE RECEIPTS (
    ID VARCHAR(255) NOT NULL,
    MONEY VARCHAR(255) NOT NULL,
    DATENEW DATETIME NOT NULL,
    POSNO VARCHAR(6) NOT NULL,
    MONEYDAY VARCHAR(255) NOT NULL,
    ATTRIBUTES MEDIUMBLOB,
    UPDATED DATETIME NOT NULL,
    ISCREDITSALE VARCHAR(1) DEFAULT 'N',
    ISCREDITINVOICED VARCHAR(1) DEFAULT 'N',
    PRIMARY KEY(ID),
    CONSTRAINT RECEIPTS_FK_MONEY FOREIGN KEY (MONEY) REFERENCES CLOSEDCASH(MONEY),
    CONSTRAINT RECEIPTS_FK_MONEYDAY FOREIGN KEY (MONEYDAY) REFERENCES CLOSEDDAY(MONEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX RECEIPTS_INX_1 ON RECEIPTS(DATENEW);

CREATE TABLE RECEIPTSHISTORY (
    ID VARCHAR(255) NOT NULL,
    MONEY VARCHAR(255) NOT NULL,
    DATENEW DATETIME NOT NULL,
    POSNO VARCHAR(6) NOT NULL,
    MONEYDAY VARCHAR(255) NOT NULL,
    ATTRIBUTES MEDIUMBLOB,
    PRIMARY KEY(ID),
    CONSTRAINT TEMPRECEIPTS_FK_MONEY FOREIGN KEY (MONEY) REFERENCES CLOSEDCASH(MONEY),
    CONSTRAINT TEMPRECEIPTS_FK_MONEYDAY FOREIGN KEY (MONEYDAY) REFERENCES CLOSEDDAY(MONEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX TEMPRECEIPTS_INX_1 ON RECEIPTS(DATENEW);

CREATE TABLE FLOORS (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    IMAGE MEDIUMBLOB,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX FLOORS_NAME_INX ON FLOORS(NAME);
--INSERT INTO FLOORS(ID, NAME, IMAGE) VALUES ('0', 'Restaurant floor', $FILE{/com/openbravo/pos/templates/restaurantsample.png});

CREATE TABLE PLACES (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    X INTEGER NOT NULL,
    Y INTEGER NOT NULL,
    FLOOR VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT PLACES_FK_1 FOREIGN KEY (FLOOR) REFERENCES FLOORS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX PLACES_NAME_INX ON PLACES(NAME);
--INSERT INTO PLACES(ID, NAME, X, Y, FLOOR) VALUES ('1', 'Table 1', 133, 151, '0');
--INSERT INTO PLACES(ID, NAME, X, Y, FLOOR) VALUES ('2', 'Table 2', 532, 151, '0');
--INSERT INTO PLACES(ID, NAME, X, Y, FLOOR) VALUES ('3', 'Table 3', 133, 264, '0');
--INSERT INTO PLACES(ID, NAME, X, Y, FLOOR) VALUES ('4', 'Table 4', 266, 264, '0');
--INSERT INTO PLACES(ID, NAME, X, Y, FLOOR) VALUES ('5', 'Table 5', 399, 264, '0');
--INSERT INTO PLACES(ID, NAME, X, Y, FLOOR) VALUES ('6', 'Table 6', 532, 264, '0');
--INSERT INTO PLACES(ID, NAME, X, Y, FLOOR) VALUES ('7', 'Table 7', 133, 377, '0');
--INSERT INTO PLACES(ID, NAME, X, Y, FLOOR) VALUES ('8', 'Table 8', 266, 377, '0');
--INSERT INTO PLACES(ID, NAME, X, Y, FLOOR) VALUES ('9', 'Table 9', 399, 377, '0');
--INSERT INTO PLACES(ID, NAME, X, Y, FLOOR) VALUES ('10', 'Table 10', 532, 377, '0');

CREATE TABLE DISCOUNTREASON (
  ID varchar(255) NOT NULL,
  REASON varchar(255) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TICKETS (
    ID VARCHAR(255) NOT NULL,
    TICKETTYPE INTEGER DEFAULT 0 NOT NULL,
    DOCUMENTNO VARCHAR(50) DEFAULT NULL,
    TICKETID INTEGER NOT NULL,
    PERSON VARCHAR(255) NOT NULL,
    CUSTOMER VARCHAR(255),
    STATUS INTEGER DEFAULT 0 NOT NULL,
    BILLDISCOUNT DOUBLE(6,1) NOT NULL,
    LEASTVALUEDISCOUNT DOUBLE(6,1) NOT NULL,
    CUSTOMERDISCOUNT DOUBLE(6,2) NOT NULL DEFAULT '0',
    DISCOUNTRATE VARCHAR(6) NOT NULL DEFAULT '0',
    ISHOMEDELIVERY VARCHAR(1),
    DELIVERYBOY VARCHAR(255),
    ADVANCEISSUED DOUBLE(10,0) NOT NULL DEFAULT '0',
    ISCOD VARCHAR(1),
    DELIVEREDTO VARCHAR(60) DEFAULT NULL,
    ADVANCERETURNED DOUBLE(6,2) NOT NULL DEFAULT '0',
    COLLECTEDAMOUNT DOUBLE(6,2) NOT NULL DEFAULT '0',
    DELIVERYSTATUS VARCHAR(1) NOT NULL DEFAULT 'N',
    COMPLETED VARCHAR(1) NOT NULL DEFAULT 'N',
    BILLAMOUNT DOUBLE(10,2) NOT NULL DEFAULT '0',
    DELIVEREDDATE DATETIME DEFAULT NULL,
    CREDITAMOUNT DOUBLE(10,2) NOT NULL DEFAULT '0',
    ISCREDITSALE VARCHAR(1) NOT NULL DEFAULT 'N',
    ISPAIDSTATUS VARCHAR(1) NOT NULL DEFAULT 'Y',
    BILLPROMOID VARCHAR(25) DEFAULT NULL,
    TIPS DOUBLE(6,0) NOT NULL DEFAULT '0',
    TABLEID VARCHAR(255) DEFAULT NULL,
    SERVICETAXID VARCHAR(255) DEFAULT NULL,
    SERVICETAXAMT DOUBLE(6,2) NOT NULL DEFAULT '0',
    SERVICECHARGEID VARCHAR(255) DEFAULT NULL,
    SERVICECHARGEAMT DOUBLE(6,2) NOT NULL DEFAULT '0',
    ISTAKEAWAY VARCHAR(1) NOT NULL DEFAULT 'N',
    ISNONCHARGABLE VARCHAR(1) NOT NULL DEFAULT 'N',
    NOOFCOVERS INT(10) NOT NULL DEFAULT 0,
    HDCUSTOMERADDRESS VARCHAR(255) DEFAULT NULL,
    ROUNDOFFVALUE DOUBLE(6,2) NOT NULL DEFAULT '0',
    ISCANCELTICKET varchar(1) NOT NULL DEFAULT 'N',
    CANCELREASONID varchar(255) DEFAULT NULL,
    CANCELCOMMENTS varchar(255) DEFAULT NULL,
    PARENTBILLNO varchar(50) DEFAULT NULL,
    DISCOUNTREASONID varchar(255) DEFAULT NULL,
    CONTENT mediumblob,
    REPRINTREASON varchar(255) DEFAULT NULL,
    DISCOUNTREASON varchar(255) DEFAULT NULL,
    RESETTLEREASON VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT DISCOUNT_REASON_ID FOREIGN KEY (DISCOUNTREASONID) REFERENCES DISCOUNTREASON (ID),
    CONSTRAINT TICKETS_FK_ID FOREIGN KEY (ID) REFERENCES RECEIPTS(ID),
    CONSTRAINT TICKETS_FK_2 FOREIGN KEY (PERSON) REFERENCES PEOPLE(ID),
    CONSTRAINT TICKETS_CUSTOMERS_FK FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMERS(ID),
    CONSTRAINT TICKETS_TABLE_ID FOREIGN KEY (TABLEID) REFERENCES PLACES (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE INDEX TICKETS_TICKETID ON TICKETS(TICKETTYPE, TICKETID);

CREATE TABLE TICKETSHISTORY (
    ID VARCHAR(255) NOT NULL,
    TICKETTYPE INTEGER DEFAULT 0 NOT NULL,
    DOCUMENTNO VARCHAR(50) DEFAULT NULL,
    TICKETID INTEGER NOT NULL,
    PERSON VARCHAR(255) NOT NULL,
    CUSTOMER VARCHAR(255),
    STATUS INTEGER DEFAULT 0 NOT NULL,
    BILLDISCOUNT DOUBLE(6,1) NOT NULL,
    LEASTVALUEDISCOUNT DOUBLE(6,1) NOT NULL,
    CUSTOMERDISCOUNT DOUBLE(6,0) NOT NULL DEFAULT '0',
    DISCOUNTRATE VARCHAR(6) NOT NULL DEFAULT '0',
    ISHOMEDELIVERY VARCHAR(1),
    DELIVERYBOY VARCHAR(255),
    ADVANCEISSUED DOUBLE(10,0) NOT NULL DEFAULT '0',
    ISCOD VARCHAR(1),
    DELIVEREDTO VARCHAR(60) DEFAULT NULL,
    ADVANCERETURNED DOUBLE(6,2) NOT NULL DEFAULT '0',
    COLLECTEDAMOUNT DOUBLE(6,2) NOT NULL DEFAULT '0',
    DELIVERYSTATUS VARCHAR(1) NOT NULL DEFAULT 'N',
    COMPLETED VARCHAR(1) NOT NULL DEFAULT 'N',
    BILLAMOUNT DOUBLE(10,2) NOT NULL DEFAULT '0',
    DELIVEREDDATE DATETIME DEFAULT NULL,
    CREDITAMOUNT DOUBLE(10,2) NOT NULL DEFAULT '0',
    PRIMARY KEY (ID),
    CONSTRAINT HISTICKETS_FK_ID FOREIGN KEY (ID) REFERENCES RECEIPTSHISTORY(ID),
    CONSTRAINT HISTICKETS_FK_2 FOREIGN KEY (PERSON) REFERENCES PEOPLE(ID),
    CONSTRAINT HISTICKETS_CUSTOMERS_FK FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMERS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX HISTICKETS_TICKETID ON TICKETS(TICKETTYPE, TICKETID);

CREATE TABLE TICKETSNUM (ID INTEGER NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--INSERT INTO TICKETSNUM VALUES(1);

CREATE TABLE TICKETSNUM_REFUND (ID INTEGER NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--INSERT INTO TICKETSNUM_REFUND VALUES(1);

CREATE TABLE TICKETSNUM_PAYMENT (ID INTEGER NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--INSERT INTO TICKETSNUM_PAYMENT VALUES(1);

CREATE TABLE TICKETLINES (
    TICKET VARCHAR(255) NOT NULL,
    LINE INTEGER NOT NULL,
    PRODUCT VARCHAR(255),
    ATTRIBUTESETINSTANCE_ID VARCHAR(255),
    UNITS DOUBLE NOT NULL,
    DISCOUNT DOUBLE(6,0) NOT NULL,
    PRICE DOUBLE NOT NULL,
    DISCOUNTPRICE DOUBLE(6,2) NOT NULL,
    TAXID VARCHAR(255) NOT NULL,
    ATTRIBUTES MEDIUMBLOB,
    PROMOTIONCAMPAIGNID VARCHAR(255) DEFAULT NULL,
    KOTID int(20) NOT NULL,
    TABLEID varchar(255) DEFAULT NULL,
    INSTRUCTION varchar(255) DEFAULT NULL,
    PERSON varchar(255) DEFAULT NULL,
    KOTDATE datetime DEFAULT NULL,
    SERVICECHARGEID varchar(255) DEFAULT NULL,
    SERVICETAXID varchar(255) DEFAULT NULL,
    PRIMARY KEY (TICKET, LINE),
    CONSTRAINT TICKETLINES_FK_TICKET FOREIGN KEY (TICKET) REFERENCES TICKETS(ID),
    CONSTRAINT TICKETLINES_FK_2 FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID),
    CONSTRAINT TICKETLINES_ATTSETINST FOREIGN KEY (ATTRIBUTESETINSTANCE_ID) REFERENCES ATTRIBUTESETINSTANCE(ID),
    CONSTRAINT TICKETLINES_FK_3 FOREIGN KEY (TAXID) REFERENCES TAXES(ID),
    CONSTRAINT TICKETLINES_IBFK_1 FOREIGN KEY (SERVICECHARGEID) REFERENCES SERVICECHARGE (ID),
    CONSTRAINT TICKETLINES_IBFK_2 FOREIGN KEY (SERVICETAXID) REFERENCES TAXES (ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TICKETLINESHISTORY (
    TICKET VARCHAR(255) NOT NULL,
    LINE INTEGER NOT NULL,
    PRODUCT VARCHAR(255),
    ATTRIBUTESETINSTANCE_ID VARCHAR(255),
    UNITS DOUBLE NOT NULL,
    DISCOUNT DOUBLE(6,0) NOT NULL,
    PRICE DOUBLE NOT NULL,
    DISCOUNTPRICE DOUBLE(6,2) NOT NULL,
    TAXID VARCHAR(255) NOT NULL,
    ATTRIBUTES MEDIUMBLOB,
    PROMOTIONCAMPAIGNID VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (TICKET, LINE),
    CONSTRAINT HISTICKETLINES_FK_TICKET FOREIGN KEY (TICKET) REFERENCES TICKETSHISTORY(ID),
    CONSTRAINT HISTICKETLINES_FK_2 FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID),
    CONSTRAINT HIS_ATTSETINST FOREIGN KEY (ATTRIBUTESETINSTANCE_ID) REFERENCES ATTRIBUTESETINSTANCE(ID),
    CONSTRAINT HISTICKETLINES_FK_3 FOREIGN KEY (TAXID) REFERENCES TAXES(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PAYMENTS (
    ID VARCHAR(255) NOT NULL,
    RECEIPT VARCHAR(255) NOT NULL,
    PAYMENT VARCHAR(255) NOT NULL,
    TOTAL DOUBLE NOT NULL,
    TRANSID VARCHAR(255),
    RETURNMSG MEDIUMBLOB,
    CHEQUENOS VARCHAR(255),
    PRIMARY KEY (ID),
    CONSTRAINT PAYMENTS_FK_RECEIPT FOREIGN KEY (RECEIPT) REFERENCES RECEIPTS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX PAYMENTS_INX_1 ON PAYMENTS(PAYMENT);

CREATE TABLE PAYMENTSHISTORY (
    ID VARCHAR(255) NOT NULL,
    RECEIPT VARCHAR(255) NOT NULL,
    PAYMENT VARCHAR(255) NOT NULL,
    TOTAL DOUBLE NOT NULL,
    TRANSID VARCHAR(255),
    RETURNMSG MEDIUMBLOB,
    CHEQUENOS VARCHAR(255),
    PRIMARY KEY (ID),
    CONSTRAINT HISPAYMENTS_FK_RECEIPT FOREIGN KEY (RECEIPT) REFERENCES RECEIPTSHISTORY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX HISPAYMENTS_INX_1 ON PAYMENTS(PAYMENT);

CREATE TABLE PAYMENTSPLITS (
  ID varchar(255) NOT NULL,
  PAYMENTS_ID VARCHAR(255) NOT NULL,
  IDENTIFIER VARCHAR(50) NOT NULL,
  AMOUNT DOUBLE NOT NULL,
  PRIMARY KEY  (ID),
  KEY PAYMENTSPLITS (PAYMENTS_ID),
  CONSTRAINT PAYMENTSPLITS_FK_PAYMENTS FOREIGN KEY (PAYMENTS_ID) REFERENCES PAYMENTS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE TAXLINES (
    ID VARCHAR(255) NOT NULL,
    RECEIPT VARCHAR(255) NOT NULL,
    TAXID VARCHAR(255) NOT NULL,
    BASE DOUBLE NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT TAXLINES_TAX FOREIGN KEY (TAXID) REFERENCES TAXES(ID),
    CONSTRAINT TAXLINES_RECEIPT FOREIGN KEY (RECEIPT) REFERENCES RECEIPTS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TAXLINESHISTORY (
    ID VARCHAR(255) NOT NULL,
    RECEIPT VARCHAR(255) NOT NULL,
    TAXID VARCHAR(255) NOT NULL,
    BASE DOUBLE NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT HISTAXLINES_TAX FOREIGN KEY (TAXID) REFERENCES TAXES(ID),
    CONSTRAINT HISTAXLINES_RECEIPT FOREIGN KEY (RECEIPT) REFERENCES RECEIPTSHISTORY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE ATTENDANCEREASON (
    ID VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CURRENCYDENOMINATIONS (
  ID VARCHAR(255) NOT NULL,
  CURRENCYNAME VARCHAR(100) default NULL,
  DENOMINATIONS VARCHAR(255) default NULL,
  PRIMARY KEY  (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--INSERT INTO CURRENCYDENOMINATIONS(ID, CURRENCYNAME, DENOMINATIONS) VALUES ('001','IN','1000,500,100,50,20,10,5,2,1');
--INSERT INTO CURRENCYDENOMINATIONS(ID, CURRENCYNAME, DENOMINATIONS) VALUES ('002','US','100,50,20,10,5,2,1,0.10,0.05,0.01');
--INSERT INTO CURRENCYDENOMINATIONS(ID, CURRENCYNAME, DENOMINATIONS) VALUES ('003','GB','5,2,1,0.50,0.25,0.20,0.10,0.05,0.02,0.01,0.005');

CREATE TABLE PEOPLELOG (
  ID VARCHAR(255) NOT NULL,
  PEOPLE_ID VARCHAR(255) NOT NULL,
  STARTTIME TIMESTAMP NOT NULL,
  REASON VARCHAR(50) NOT NULL,
  POSNO VARCHAR(6) NOT NULL,
  PRIMARY KEY  (ID),
  CONSTRAINT PEOPLELOG_FK_1 FOREIGN KEY (PEOPLE_ID) REFERENCES PEOPLE (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CASHSETUP (
  ID VARCHAR(255) NOT NULL,
  DATE DATE,
  FLOATCASH DOUBLE(10,1) NOT NULL,
  PETTYCASH DOUBLE(10,1) NOT NULL,
  AUTOFLOAT VARCHAR(1) DEFAULT 'N' NOT NULL,
  RESETPERIOD VARCHAR(1) DEFAULT NULL,
  RESETDATE INT(2) DEFAULT NULL,
  RESETDAY VARCHAR(10) DEFAULT NULL,
  CREATED DATETIME,
  CREATEDBY VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE CHECKINOUT (
  ID VARCHAR(255) NOT NULL,
  EMPLOYEEID VARCHAR(255) DEFAULT NULL,
  CHECKIN VARCHAR(10) DEFAULT NULL,
  CHECKOUT VARCHAR(10) DEFAULT NULL,
  SYSTEMCHECKINTIME VARCHAR(100) DEFAULT NULL,
  SYSTEMCHECKOUTTIME VARCHAR(100) DEFAULT NULL,
  EMPCHECKINTIME VARCHAR(100) DEFAULT NULL,
  EMPCHECKOUTTIME VARCHAR(100) DEFAULT NULL,
  CURRENTDATE DATETIME DEFAULT NULL,
  CHECKINDESCID VARCHAR(255) DEFAULT NULL,
  CHECKINDESC VARCHAR(255) DEFAULT NULL,
  CHECKOUTDESCID VARCHAR(255) DEFAULT NULL,
  CHECKOUTDESC VARCHAR(255) DEFAULT NULL,
  OTHERCHECKINDESC VARCHAR(255) DEFAULT NULL,
  OTHERCHECKOUTDESC VARCHAR(255) DEFAULT NULL,
  CHECKINATTENDANCEAPPROVAL VARCHAR(10) DEFAULT NULL,
  CHECKOUTATTENDANCEAPPROVAL VARCHAR(10) DEFAULT NULL,
  LASTCHECKOUTSTATUS VARCHAR(10) DEFAULT 'N' NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE CREDITNOTE (
  ID varchar(255) NOT NULL,
  CREDITNOTENO VARCHAR(50) DEFAULT NULL,
  TICKETID INT(10) NOT NULL,
  CUSTOMER VARCHAR(255) DEFAULT NULL,
  AMOUNT DOUBLE(10,1) NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATEDBY VARCHAR(255) NOT NULL,
  UPDATEDBY VARCHAR(255) NOT NULL,
  CREATED DATETIME NOT NULL,
  UPDATED DATETIME NOT NULL,
  VALIDITY DATETIME NOT NULL,
  PRIMARY KEY (Id),
  KEY CREDITUPDATE_1 (UPDATED),
  KEY CREDITCREATE_1 (CREATED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE CURRENCYRECONCILIATION (
  ID VARCHAR(255) NOT NULL,
  DENOMINATIONID VARCHAR(255) DEFAULT NULL,
  RUPEES INT(10) DEFAULT NULL,
  COUNT INT(10) DEFAULT NULL,
  TOTAL INT(10) DEFAULT NULL,
  DATE DATETIME DEFAULT NULL,
  COMMENT VARCHAR(255) DEFAULT NULL,
  POSNO VARCHAR(6) NOT NULL,
  DENOMINATIONVALUE DOUBLE(10,1) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE FLOATCASH (
  ID VARCHAR(255) NOT NULL,
  FLOATCASH DOUBLE(10,1) NOT NULL,
  POSNO VARCHAR(6) NOT NULL,
  CREATED DATETIME NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PETTYCASH (
  ID VARCHAR(255) NOT NULL,
  PETTYCASHDATE DATE NOT NULL,
  PETTYSTATUS VARCHAR(10) NOT NULL,
  REASON VARCHAR(255) NOT NULL,
  PETTYCASH DOUBLE(10,1) NOT NULL,
  AMOUNT DOUBLE(10,1) NOT NULL,
  BALANCEAMT DOUBLE(10,1) DEFAULT '0.0' NOT NULL,
  CREATED datetime NOT NULL,
  CREATEDBY VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PURCHASEORDER (
  ID VARCHAR(255) NOT NULL,
  DOCUMENTNUMBER VARCHAR(50) DEFAULT NULL,
  VENDOR VARCHAR(255) DEFAULT NULL,
  CREATED VARCHAR(100) DEFAULT NULL,
  DELIVERY VARCHAR(100) DEFAULT NULL,
  STATUS VARCHAR(50) DEFAULT NULL,
  TOTAL DOUBLE(10,0) DEFAULT '0',
  SUBTOTAL DOUBLE(10,0) DEFAULT '0',
  TAX VARCHAR(50) DEFAULT NULL,
  GOODSRECEIPTSTATUS VARCHAR(1) DEFAULT 'N',
  CREATEDBY VARCHAR(255) DEFAULT NULL,
  ISCLOSED VARCHAR(1) DEFAULT 'N',
  ISINVOICE VARCHAR(1) DEFAULT 'N',
  PRIMARY KEY (ID),
  CONSTRAINT CUSTOMERS_FK_ID FOREIGN KEY (VENDOR) REFERENCES CUSTOMERS(ID),
  UNIQUE KEY DOCUMENTNUMBER (DOCUMENTNUMBER)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX DOCUMENTNUMBER_INX ON PURCHASEORDER(DOCUMENTNUMBER);

CREATE TABLE PURCHASEORDERLINES (
  ID VARCHAR(255) NOT NULL,
  POID VARCHAR(255) NOT NULL,
  PRODUCTID VARCHAR(255) DEFAULT NULL,
  QUANTITY DOUBLE(10,2) DEFAULT NULL,
  PRICE DOUBLE(10,0) DEFAULT NULL,
  TAXID VARCHAR(255) DEFAULT NULL,
  ISPENDINGQUANTITYMODIFIED VARCHAR(10) DEFAULT 'N' NOT NULL,
  TAXCATEGORYID VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT POID_FK_ID FOREIGN KEY (POID) REFERENCES PURCHASEORDER(ID),
  CONSTRAINT POPRODUCT_FK_2 FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID),
  CONSTRAINT POTAX_FK_3 FOREIGN KEY (TAXID) REFERENCES TAXES(ID)
)  ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE PURCHASEINVOICE (
  ID VARCHAR(255) NOT NULL,
  DOCUMENTNUMBER VARCHAR(50) DEFAULT NULL,
  VENDOR VARCHAR(255) DEFAULT NULL,
  CREATED VARCHAR(100) DEFAULT NULL,
  DELIVERY VARCHAR(100) DEFAULT NULL,
  STATUS VARCHAR(50) DEFAULT NULL,
  TOTAL DOUBLE(10,0) DEFAULT '0',
  SUBTOTAL DOUBLE(10,0) DEFAULT '0',
  TAX VARCHAR(50) DEFAULT NULL,
  GOODSRECEIPTSTATUS VARCHAR(1) DEFAULT 'N',
  CREATEDBY VARCHAR(255) DEFAULT NULL,
  ISCLOSED VARCHAR(1) DEFAULT 'N',
  POID VARCHAR(255) DEFAULT NULL,
  GRNID VARCHAR(255) DEFAULT NULL,
  CHARGESTOTAL DOUBLE(10,2) DEFAULT '0',
  DISCOUNTTOTAL DOUBLE(10,2) DEFAULT '0',
  ROUNDOFFVALUE DOUBLE(6,2) DEFAULT '0',
  PRIMARY KEY (ID),
  CONSTRAINT PICUSTOMERS_FK_ID FOREIGN KEY (VENDOR) REFERENCES CUSTOMERS(ID),
  UNIQUE KEY DOCUMENTNUMBER (DOCUMENTNUMBER)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX PIDOCUMENTNUMBER_INX ON PURCHASEINVOICE (DOCUMENTNUMBER);

CREATE TABLE PURCHASEINVOICELINES (
  ID VARCHAR(255) NOT NULL,
  POID VARCHAR(255) NOT NULL,
  PRODUCTID VARCHAR(255) DEFAULT NULL,
  QUANTITY DOUBLE(10,2) DEFAULT NULL,
  PRICE DOUBLE(10,0) DEFAULT NULL,
  TAXID VARCHAR(255) DEFAULT NULL,
  ISPENDINGQUANTITYMODIFIED VARCHAR(10) DEFAULT 'N' NOT NULL,
  TAXCATEGORYID VARCHAR(255) DEFAULT NULL,
DISCOUNT DOUBLE(10,0) DEFAULT '0',
  PRIMARY KEY (ID),
  CONSTRAINT PIID_FK_ID FOREIGN KEY (POID) REFERENCES PURCHASEINVOICE(ID),
  CONSTRAINT PIPRODUCT_FK_2 FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID),
  CONSTRAINT P1TAX_FK_3 FOREIGN KEY (TAXID) REFERENCES TAXES(ID)

)  ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE PURCHASEINVOICECHARGES (
  ID VARCHAR(255) NOT NULL,
  PIID VARCHAR(255) NOT NULL,
  CHARGEID VARCHAR(255) NOT NULL,
  CHARGENAME VARCHAR(60) NOT NULL,
  AMOUNT DOUBLE(10,2) NOT NULL,
  PRIMARY KEY  (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE GOODSRECEIPTS (
  ID VARCHAR(255) NOT NULL,
  DOCUMENTNUMBER VARCHAR(50) DEFAULT NULL,
  VENDOR VARCHAR(255) DEFAULT NULL,
  CREATED VARCHAR(100) DEFAULT NULL,
  DELIVERY VARCHAR(100) DEFAULT NULL,
  STATUS VARCHAR(50) DEFAULT NULL,
  TOTAL double(10,0) DEFAULT '0',
  SUBTOTAL double(10,0) DEFAULT '0',
  TAX VARCHAR(50) DEFAULT NULL,
  GOODSRECEIPTSTATUS VARCHAR(1) DEFAULT 'N',
  CREATEDBY VARCHAR(255) DEFAULT NULL,
  ISCLOSED VARCHAR(1) DEFAULT 'N',
  ISINVOICE VARCHAR(1) DEFAULT 'N',
  LOCATION VARCHAR(255) NOT NULL,
  PRIMARY KEY  (ID),
CONSTRAINT GRNCUSTOMERS_FK_ID FOREIGN KEY (VENDOR) REFERENCES CUSTOMERS(ID),
  UNIQUE KEY DOCUMENTNUMBER (DOCUMENTNUMBER),
  UNIQUE KEY DOCUMENTNUMBER_INX (DOCUMENTNUMBER)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE GOODSRECEIPTLINES (
  ID varchar(255) NOT NULL,
  RECEIPTID varchar(255) NOT NULL,
  PRODUCTID varchar(255) default NULL,
  QUANTITY double(10,2) default NULL,
  PRICE double(10,0) default NULL,
  TAXID varchar(255) default NULL,
  ISPENDINGQUANTITYMODIFIED varchar(10) NOT NULL default 'N',
  TAXCATEGORYID varchar(255) default NULL,
  PRIMARY KEY  (ID),
  CONSTRAINT GRNID_FK_ID FOREIGN KEY (RECEIPTID) REFERENCES GOODSRECEIPTS(ID),
  CONSTRAINT GRNPRODUCT_FK_2 FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID),
  CONSTRAINT GRNTAX_FK_3 FOREIGN KEY (TAXID) REFERENCES TAXES(ID)

) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE GOODSRETURN (
  ID VARCHAR(255) NOT NULL,
  DOCUMENTNUMBER VARCHAR(50) DEFAULT NULL,
  VENDOR VARCHAR(255) DEFAULT NULL,
  CREATED VARCHAR(100) DEFAULT NULL,
  DELIVERY VARCHAR(100) DEFAULT NULL,
  STATUS VARCHAR(50) DEFAULT NULL,
  TOTAL double(10,0) DEFAULT '0',
  SUBTOTAL double(10,0) DEFAULT '0',
  TAX VARCHAR(50) DEFAULT NULL,
  GOODSRETURNSTATUS VARCHAR(1) DEFAULT 'N',
  CREATEDBY VARCHAR(255) DEFAULT NULL,
  ISCLOSED VARCHAR(1) DEFAULT 'N',
  LOCATION VARCHAR(255) NOT NULL,
  PRIMARY KEY  (ID),
CONSTRAINT GRRCUSTOMERS_FK_ID FOREIGN KEY (VENDOR) REFERENCES CUSTOMERS(ID),
  UNIQUE KEY DOCUMENTNUMBER (DOCUMENTNUMBER),
  UNIQUE KEY DOCUMENTNUMBER_INX (DOCUMENTNUMBER)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE GOODSRETURNLINES (
  ID varchar(255) NOT NULL,
  RETURNID varchar(255) NOT NULL,
  PRODUCTID varchar(255) default NULL,
  QUANTITY double(10,2) default NULL,
  PRICE double(10,0) default NULL,
  TAXID varchar(255) default NULL,
  ISPENDINGQUANTITYMODIFIED varchar(10) NOT NULL default 'N',
  TAXCATEGORYID varchar(255) default NULL,
  PRIMARY KEY  (ID),
  CONSTRAINT GRRID_FK_ID FOREIGN KEY (RETURNID) REFERENCES GOODSRETURN(ID),
  CONSTRAINT GRRPRODUCT_FK_2 FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID),
  CONSTRAINT GRRTAX_FK_3 FOREIGN KEY (TAXID) REFERENCES TAXES(ID)

) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE GOODSMOVEMENT (
  ID VARCHAR(255) NOT NULL,
  DOCUMENTNUMBER VARCHAR(50) DEFAULT NULL,
  CREATED VARCHAR(100) DEFAULT NULL,
  TOTAL double(10,0) DEFAULT '0',
  SUBTOTAL double(10,0) DEFAULT '0',
  TAX VARCHAR(50) DEFAULT NULL,
  CREATEDBY VARCHAR(255) DEFAULT NULL,
  TOLOCATION VARCHAR(255) NOT NULL,
  FROMLOCATION VARCHAR(255) NOT NULL,
  PROCESSED CHAR(1) NOT NULL DEFAULT '0',
  PRIMARY KEY  (ID),
  UNIQUE KEY DOCUMENTNUMBER (DOCUMENTNUMBER),
  UNIQUE KEY DOCUMENTNUMBER_INX (DOCUMENTNUMBER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE GOODSMOVEMENTLINES (
  ID varchar(255) NOT NULL,
  RECEIPTID varchar(255) NOT NULL,
  PRODUCTID varchar(255) default NULL,
  QUANTITY double(10,2) default NULL,
  PRICE double(10,2) default NULL,
  TAXID varchar(255) default NULL,
  TAXCATEGORYID varchar(255) default NULL,
  AVAILABLEQTY double(6,0) NOT NULL DEFAULT '0',
  PRIMARY KEY  (ID),
  CONSTRAINT GMID_FK_ID FOREIGN KEY (RECEIPTID) REFERENCES GOODSMOVEMENT(ID),
  CONSTRAINT GMPRODUCT_FK_2 FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID),
  CONSTRAINT GMTAX_FK_3 FOREIGN KEY (TAXID) REFERENCES TAXES(ID)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CHARGESMASTER (
  ID varchar(255) NOT NULL,
  NAME varchar(60) NOT NULL,
  ACCOUNT varchar(60) NOT NULL,
  ISDISCOUNTS varchar(1) DEFAULT 'N',
  PRIMARY KEY  (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE STOCKRECONCILIATION (
  ID VARCHAR(255) NOT NULL,
  DOCUMENTNO VARCHAR(20) NOT NULL,
  DATE DATETIME NOT NULL,
  CATEGORY VARCHAR(255) DEFAULT NULL,
  WAREHOUSE VARCHAR(255) DEFAULT NULL,
  RECONCILE VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY  (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE STOCKRECONCILIATIONLINES (
  ID VARCHAR(255) NOT NULL,
  ITEM VARCHAR(255) NOT NULL,
  SYSTEMQTY DOUBLE(10,1) NOT NULL,
  PHYSICALQTY DOUBLE(10,1) NOT NULL,
  VARIANCE DOUBLE(10,1) NOT NULL,
  PRICE DOUBLE(10,2) NOT NULL,
  REMARKS VARCHAR(255) NOT NULL,
CONSTRAINT STOCKID_FK_ID FOREIGN KEY (ID) REFERENCES STOCKRECONCILIATION(ID)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE STOCKRECONCILIATIONSTATUS (
  ID VARCHAR(255) NOT NULL,
  ISSTOPINVENTORY VARCHAR(1) NOT NULL,
  PRIMARY KEY  (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PROMOTIONCAMPAIGN (
  ID VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  STARTDATE DATE NOT NULL,
  STARTTIME TIME NOT NULL,
  ENDDATE DATE NOT NULL,
  ENDTIME TIME NOT NULL,
  WEEKDAY VARCHAR(1) DEFAULT 'N',
  WEEKENDS VARCHAR(1) DEFAULT 'N',
  ALLDAY VARCHAR(1) DEFAULT 'N' NOT NULL,
  SUNDAY VARCHAR(1) DEFAULT 'N' NOT NULL,
  MONDAY VARCHAR(1)DEFAULT 'N' NOT NULL,
  TUESDAY VARCHAR(1) DEFAULT 'N' NOT NULL,
  WEDNESDAY VARCHAR(1) DEFAULT 'N' NOT NULL,
  THURSDAY VARCHAR(1) DEFAULT 'N' NOT NULL,
  FRIDAY VARCHAR(1) DEFAULT 'N' NOT NULL,
  SATURDAY VARCHAR(1) DEFAULT 'N' NOT NULL,
  ACTIVE VARCHAR(1) DEFAULT 'N' NOT NULL,
  PRIMARY KEY  (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PROMOTIONTYPE (
  ID VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY  (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PROMOTIONRULE (
  ID VARCHAR(255) NOT NULL,
  PROMOTIONCAMPAIGNID VARCHAR(255) NOT NULL,
  PROMOTIONTYPEID VARCHAR(255) NOT NULL,
  BUYQTY DOUBLE(6,0) DEFAULT 0,
  GETQTY DOUBLE(6,0) DEFAULT 0,
  BILLAMOUNT DOUBLE(6,0) DEFAULT 0,
  MINVALUE DOUBLE(6,0) DEFAULT 0,
  ISPRICE VARCHAR(1) DEFAULT 'N' NOT NULL,
  VALUE DOUBLE(6,0) DEFAULT 0,
  ISPROMOPRODUCT VARCHAR(1) DEFAULT 'N' NOT NULL,
  ISCROSSPROMOPRODUCT VARCHAR(1) DEFAULT 'N' NOT NULL,
  ISMULTIPLEPROMOPRODUCT VARCHAR(1) DEFAULT 'N' NOT NULL,
  ISMULTIPLECROSSPROMOPRODUCT VARCHAR(1) DEFAULT 'N' NOT NULL,
  ISSKU VARCHAR(1) DEFAULT 'N' NOT NULL,
  MINIMUMRANGE INT(6) DEFAULT 0,
  MAXIMUMRANGE INT(6) DEFAULT 0,
  PRIMARY KEY  (ID),
CONSTRAINT PTNCAMPAIGNID_FK FOREIGN KEY (PROMOTIONCAMPAIGNID) REFERENCES PROMOTIONCAMPAIGN(ID),
  CONSTRAINT PTNTYPEID_FK FOREIGN KEY (PROMOTIONTYPEID) REFERENCES PROMOTIONTYPE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE CROSSPROMOPRODUCT (
  ID VARCHAR(255) NOT NULL,
  PROMOTIONRULEID VARCHAR(255) NOT NULL,
  PRODUCTID VARCHAR(255) NOT NULL,
  ISMULIPLE VARCHAR(1) DEFAULT 'N' NOT NULL,
  PRIMARY KEY  (ID),
  CONSTRAINT PROMOTIONRULEID_FK FOREIGN KEY (PROMOTIONRULEID) REFERENCES PROMOTIONRULE(ID),
  CONSTRAINT PRODUCTID_FK FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PROMOPRODUCT (
  ID VARCHAR(255) NOT NULL,
  PROMOTIONRULEID VARCHAR(255) NOT NULL,
  PRODUCTID VARCHAR(255) NOT NULL,
  ISMULTIPLE VARCHAR(1) DEFAULT 'N' NOT NULL,
  PRIMARY KEY  (ID),
  CONSTRAINT promopdtrule_FK FOREIGN KEY (PROMOTIONRULEID) REFERENCES PROMOTIONRULE(ID),
  CONSTRAINT promoproductid_FK FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE DISCOUNTRATE (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    RATE DOUBLE NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX DISCOUNTRATE_NAME_INX ON DISCOUNTRATE(NAME);



CREATE TABLE SLMLICENSEHISTORY (
  ID VARCHAR(255) NOT NULL,
  INFO1 VARCHAR(255) NOT NULL,
  INFO2 VARCHAR(255) NOT NULL,
  INFO3 VARCHAR(255) NOT NULL,
  INFO4 VARCHAR(255) NOT NULL,
  INFO5 VARCHAR(255) NOT NULL,
  INFO6 VARCHAR(255) NOT NULL,
  INFO7 VARCHAR(255) NOT NULL,
  INFO8 VARCHAR(255) NOT NULL,
  INFO9 VARCHAR(255) NOT NULL,
  INFO10 VARCHAR(255) NOT NULL,
  PRIMARY KEY  (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TEMPTICKETLINES (
  PRODUCTID VARCHAR(255) NOT NULL,
  CAMPAIGNID VARCHAR(255) DEFAULT NULL,
  PROMOTIONID VARCHAR(255) NOT NULL,
  ISCROSSPROMOPRODUCT VARCHAR(1) NOT NULL,
  QUANTITY DOUBLE(6,0) NOT NULL,
  PROMOTYPE VARCHAR(255) NOT NULL,
  PRICE DOUBLE(6,0) NOT NULL,
  BUYQTY DOUBLE(6,0) NOT NULL DEFAULT '0',
  GETQTY DOUBLE(6,0) NOT NULL DEFAULT '0',
  TAXRATE DOUBLE(6,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PROCESSINFO (
  ID VARCHAR(255) NOT NULL,
  PROCESSNAME VARCHAR(20) NOT NULL,
  COUNT INT(10) NOT NULL,
  PRIMARY KEY  (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PETTYCASHSETUP(
  ID VARCHAR(255) NOT NULL,
  PETTYCASH DOUBLE(10,1) NOT NULL,
  RESETPERIOD VARCHAR(1) DEFAULT NULL,
  RESETDATE INT(2) DEFAULT NULL,
  RESETDAY VARCHAR(10) DEFAULT NULL,
  CREATED DATETIME DEFAULT NULL,
  CREATEDBY VARCHAR(255) NOT NULL,
  PRIMARY KEY  (ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE FLOATCASHSETUP (
  ID VARCHAR(255) NOT NULL,
  DATE DATE DEFAULT NULL,
  FLOATCASH DOUBLE(10,1) NOT NULL,
  AUTOFLOAT VARCHAR(1) NOT NULL DEFAULT 'N',
  CREATED DATETIME DEFAULT NULL,
  CREATEDBY VARCHAR(255) NOT NULL,
  PRIMARY KEY  (ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE ACCOUNTINGCONFIG (
  ID varchar(255) default NULL,
  SALESTAXCREDIT varchar(60) default NULL,
  SALESCASHDEBIT varchar(60) default NULL,
  SALESCARDDEBIT varchar(60) default NULL,
  SALESCHEQUEDEBIT varchar(60) default NULL,
  PURCHASEDEBIT varchar(60) default NULL,
  PURCHASECREDIT varchar(60) default NULL,
  JOURNALDEBIT varchar(60) default NULL,
  JOURNALCREDIT varchar(60) default NULL,
  CUSTOMERDEBIT varchar(60) default NULL,
  CUSTOMERCREDIT varchar(60) default NULL,
  VENDORDEBIT varchar(60) default NULL,
  VENDORCREBIT varchar(60) default NULL,
  PORDUCTCREDIT varchar(60) default NULL,
  SALESDISCOUNTDEBIT varchar(60) default NULL,
  SALESNONTAXCREDIT varchar(60) default NULL,
  PORDUCTDEBIT varchar(60) default NULL,
  SALESSERVICETAXCREDIT varchar(60) default NULL,
  CREDIT varchar(60) default NULL,
  PURCHASENONTAXDEBIT varchar(60) default NULL,
  PURCHASEDISCOUNT varchar(60) default NULL,
  ROUNDOFFVALUE varchar(60) default NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CREDITSALE (
  ID varchar(255) NOT NULL,
  TICKETID varchar(255) NOT NULL,
  BILLNO varchar(50) NOT NULL,
  BILLDATE datetime NOT NULL,
  CUSTOMER varchar(60) NOT NULL,
  BILLAMOUNT double(6,2) NOT NULL,
  CREDITAMOUNT double(6,2) default NULL,
  ACTUALPAYMENT double(6,2) default NULL,
  PAYMENTTYPE varchar(30) default NULL,
  CHEQUENO varchar(50) default NULL,
  CHEQUEDATE date default NULL,
  BANKNAME varchar(255) default NULL,
  REMARKS varchar(255) default NULL,
  ISACTIVE varchar(1) default 'Y',
  PRIMARY KEY  (ID),
  KEY FK_TICKETID (TICKETID),
  CONSTRAINT FK_KEY_TICKETID FOREIGN KEY (TICKETID) REFERENCES RECEIPTS (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CUSTOMERSNUM (
  CUSTOMERID varchar(30) NOT NULL,
  PRIMARY KEY  (CUSTOMERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

 CREATE TABLE TALLYEXPORT (
  REMOTEID int(11) DEFAULT '1',
  VCHKEY int(11) DEFAULT '1',
  VOUCHERKEY varchar(255) DEFAULT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SERVICECHARGE (
  ID varchar(255) NOT NULL,
  NAME varchar(255) NOT NULL,
  RATE double NOT NULL,
VALIDFROM timestamp NOT NULL,
ISSUMMARY varchar(1) NOT NULL DEFAULT 'N',
BASEAMOUNT varchar(60) NOT NULL DEFAULT 'LNA' ,
SERVICECHARGEBASEID varchar(32),
DOCSERVICECHARGEAMOUNT varchar(60) NOT NULL DEFAULT 'D',
DEBITACCOUNT varchar(60) DEFAULT NULL,
CREDITACCOUNT varchar(60) DEFAULT NULL,
CATEGORY varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY SERVICECHARGE_NAME_INX (NAME),
CONSTRAINT servicecharge_chargebase FOREIGN KEY (SERVICECHARGEBASEID)
      REFERENCES SERVICECHARGE (ID),
CONSTRAINT servicecharge_cat_fk FOREIGN KEY (CATEGORY) REFERENCES taxcategories (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE RESERVATIONS (
    ID VARCHAR(255) NOT NULL,
    CREATED DATETIME NOT NULL,
    DATENEW DATETIME DEFAULT '2001-01-01 00:00:00' NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CHAIRS INTEGER NOT NULL,
    ISDONE BIT NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX RESERVATIONS_INX_1 ON RESERVATIONS(DATENEW);

CREATE TABLE TABLECOVERS (
  ID VARCHAR(255) NOT NULL,
  TABLEID VARCHAR(255) NOT NULL,
  NOOFCOVERS INT(10) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE KOT (
  ID VARCHAR(255) NOT NULL,
  TICKET VARCHAR(255) NOT NULL,
  DATENEW DATETIME NOT NULL,
  BILLNO VARCHAR(20) DEFAULT '0',
  PRODUCTID VARCHAR(60) NOT NULL,
  ISPRINTED VARCHAR(1) NOT NULL,
  QTY DOUBLE(6,0) NOT NULL,
  KOTID INT(20) NOT NULL DEFAULT '0',
  ISCANCELLED VARCHAR(1) NOT NULL DEFAULT 'N',
  REASON VARCHAR(255) DEFAULT NULL,
  REASONID VARCHAR(255) DEFAULT NULL,
  ISPRINTCANCEL VARCHAR(1) DEFAULT 'N',
  TABLEID VARCHAR(255) DEFAULT NULL,
  INSTRUCTION varchar(255) DEFAULT NULL,
  PERSON varchar(255) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE KOTNUM (
  ID int(50) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE KOTREASON (
  ID INT(6) NOT NULL,
  REASON VARCHAR(255) NOT NULL,
  STATUS VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--INSERT INTO KOTREASON(ID, REASON,STATUS) VALUES(1, 'Oily','Y' );
--INSERT INTO KOTREASON(ID, REASON,STATUS) VALUES(2, 'Others','Y' );

CREATE TABLE CANCELTICKETS (
  ID VARCHAR(255) NOT NULL,
  TICKETID int(11) NOT NULL,
  POSNO VARCHAR(1) NOT NULL,
  PERSON VARCHAR(255) NOT NULL,
  CUSTOMER VARCHAR(255) DEFAULT NULL,
  ISHOMEDELIVERY VARCHAR(1) NOT NULL DEFAULT 'N',
  BILLAMOUNT double(10,2) NOT NULL DEFAULT '0.00',
  DATENEW datetime DEFAULT NULL,
  REASON VARCHAR(255) DEFAULT NULL,
  REASONID VARCHAR(255) DEFAULT NULL,
  TABLEID VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT CANCELTICKETS_FK_2 FOREIGN KEY (PERSON) REFERENCES PEOPLE(ID),
  CONSTRAINT CANCELTICKETS_CUSTOMERS_FK FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMERS(ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE CANCELTICKETLINES (
  TICKET VARCHAR(255) NOT NULL,
  LINE INT(11) NOT NULL,
  PRODUCT VARCHAR(255) DEFAULT NULL,
  UNITS DOUBLE NOT NULL,
  PRICE DOUBLE NOT NULL,
  TAXID VARCHAR(255) NOT NULL,
  PRIMARY KEY (TICKET, LINE),
  CONSTRAINT CANCELTICKETLINES_FK_TICKET FOREIGN KEY (TICKET) REFERENCES TICKETS(ID),
  CONSTRAINT CANCELTICKETLINES_FK_2 FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID),
  CONSTRAINT CANCELTICKETLINES_FK_3 FOREIGN KEY (TAXID) REFERENCES TAXES(ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE TAXMAPPING (
  ID varchar(255) NOT NULL,
  BUSINESSTYPE varchar(255) NOT NULL,
  ISSERVICETAXINCLUDED varchar(1) NOT NULL DEFAULT 'N',
  ISSERVICECHARGEINCLUDED varchar(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (ID),
  KEY TAXMAPPING_FK_2 (BUSINESSTYPE),
  CONSTRAINT TAXMAPPING_FK_2 FOREIGN KEY (BUSINESSTYPE) REFERENCES BUSINESSTYPE (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TAXMAPPINGLINES (
  ID varchar(255) NOT NULL,
  TAXMAPID varchar(255) NOT NULL,
  TAXID varchar(255) NOT NULL,
  ISSERVICETAX varchar(1) DEFAULT 'N',
  PRIMARY KEY (ID),
  KEY TAXLINES_FK_ID (TAXMAPID),
  CONSTRAINT TAXMAPPINGLINES_FK_ID FOREIGN KEY (TAXMAPID) REFERENCES TAXMAPPING (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE RESERVATION_CUSTOMERS (
    ID VARCHAR(255) NOT NULL,
    CUSTOMER VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT RES_CUST_FK_1 FOREIGN KEY (ID) REFERENCES RESERVATIONS(ID),
    CONSTRAINT RES_CUST_FK_2 FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMERS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE THIRDPARTIES (
    ID VARCHAR(255) NOT NULL,
    CIF VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255),
    CONTACTCOMM VARCHAR(255),
    CONTACTFACT VARCHAR(255),
    PAYRULE VARCHAR(255),
    FAXNUMBER VARCHAR(255),
    PHONENUMBER VARCHAR(255),
    MOBILENUMBER VARCHAR(255),
    EMAIL VARCHAR(255),
    WEBPAGE VARCHAR(255),
    NOTES VARCHAR(255),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX THIRDPARTIES_CIF_INX ON THIRDPARTIES(CIF);
CREATE UNIQUE INDEX THIRDPARTIES_NAME_INX ON THIRDPARTIES(NAME);

CREATE TABLE SHAREDTICKETS (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CONTENT MEDIUMBLOB,
    SPLITID varchar(255) DEFAULT NULL,
    ISPRINTED tinyint(1) DEFAULT '0',
    ISMODIFIED tinyint(1) DEFAULT '0',
    PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE LOYALITYCOUPON (
  ID VARCHAR(255) NOT NULL,
  BILLNO int(11) DEFAULT '0',
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE ORDERNUM (
  ID int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE POSTERMINAL (
  ID VARCHAR(32) NOT NULL,
  SEARCHKEY VARCHAR(40) NOT NULL,
  NAME VARCHAR(60) NOT NULL,
  DESCRIPTION VARCHAR(400) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=dec8;

CREATE TABLE PRINTERCONFIG (
  ID varchar(32) NOT NULL,
  SEARCHKEY varchar(40) NOT NULL,
  NAME varchar(60) NOT NULL,
  DESCRIPTION varchar(400) NOT NULL,
  ID_1 varchar(32) DEFAULT NULL,
  PATH varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY idx_printerconfig_lookup (ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE PRODUCTIONAREA (
  ID varchar(255) NOT NULL,
  SEARCHKEY varchar(40) NOT NULL,
  NAME varchar(60) NOT NULL,
  RESTUARANTPRINTER varchar(32) NOT NULL,
  PRODUCTIONAREATYPE varchar(32) NOT NULL,
  DESCRIPTION varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PRODUCTIONAREATYPE (
  ID varchar(255) NOT NULL,
  SEARCHKEY varchar(40) NOT NULL,
  NAME varchar(60) NOT NULL,
  DESCRIPTION varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PRODUCTLINKEDADDON (
  ID varchar(32) NOT NULL,
  ADDON varchar(32) NOT NULL,
  LINKEDTO varchar(32) NOT NULL,
  DESCRIPTION varchar(400) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE PRODUCTLINKEDTO (
  ID varchar(32) NOT NULL,
  ADDON varchar(32) NOT NULL,
  LINKEDTO varchar(32) NOT NULL,
  DESCRIPTION varchar(400) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SECTIONMAPPING (
  ID varchar(32) NOT NULL,
  SECTION varchar(32) NOT NULL,
  PRODUCTIONAREATYPE varchar(32) NOT NULL,
  PRODUCTIONAREA varchar(32) NOT NULL,
  KITCHENDISPLAY varchar(32) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tbl_order (
  ORDER_ID int(11) NOT NULL AUTO_INCREMENT,
  TOKEN_ID varchar(255) NOT NULL,
  DELIVERYADDRESS_ID int(11) DEFAULT NULL,
  CUSTOMER_ID varchar(255) DEFAULT NULL,
  CUSTOMER_MOB_ID int(11) DEFAULT NULL,
  ORDERBY varchar(50) DEFAULT NULL,
  ORDERTYPE_ID int(11) DEFAULT NULL,
  MST_TABLE_ID varchar(255) DEFAULT NULL,
  USER_ID varchar(255) DEFAULT NULL,
  AMOUNT double(13,2) DEFAULT NULL,
  TAX double(13,2) DEFAULT NULL,
  TOTAL double(13,2) DEFAULT NULL,
  DELIVERYMAN_ID varchar(255) DEFAULT NULL,
  ORDERTIME datetime DEFAULT NULL,
  PREPARETIME time DEFAULT NULL,
  DELIVERYTIME datetime DEFAULT NULL,
  READYTIME datetime DEFAULT NULL,
  PAIDSTATUS tinyint(1) DEFAULT NULL,
  DISPATCHTIME datetime DEFAULT NULL,
  DELIVERYTIME_ACTUAL datetime DEFAULT NULL,
  DELIVERYTIME_RECORDED datetime DEFAULT NULL,
  DELIVERYSTATUS int(11) DEFAULT NULL,
  PREPARESTATUS tinyint(1) DEFAULT '0',
  DELIVEREDREMARKS tinyint(1) DEFAULT NULL,
  CANCELREASON varchar(50) DEFAULT NULL,
  ISPOSUPDATED tinyint(1) DEFAULT NULL,
  CREATEDDATE datetime DEFAULT NULL,
  MODIFIEDDATE datetime DEFAULT NULL,
  ACTIVE tinyint(1) NOT NULL DEFAULT '1',
  ticketid varchar(255) DEFAULT NULL,
  PRIMARY KEY (ORDER_ID)
) ENGINE=InnoDB AUTO_INCREMENT=3849 DEFAULT CHARSET=utf8;


CREATE TABLE tbl_orderitem (
  ORDERITEM_ID varchar(255) NOT NULL,
  TOKEN_ID varchar(255) NOT NULL,
  ITEM_ID varchar(255) DEFAULT NULL,
  QUANTITY int(11) DEFAULT NULL,
  PRICE double(13,2) DEFAULT NULL,
  ORDERTIME datetime DEFAULT NULL,
  PREPARETIME time DEFAULT NULL,
  PREPARESTATUS int(11) DEFAULT '0',
  BLINK int(11) NOT NULL DEFAULT '0',
  CREATEDDATE datetime DEFAULT NULL,
  MODIFIEDDATE datetime DEFAULT NULL,
  ACTIVE tinyint(1) NOT NULL DEFAULT '1',
  ITEM_CODE varchar(45) DEFAULT NULL,
  PRIMARY KEY (ORDERITEM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tbl_token (
  TOKEN_ID int(30) NOT NULL AUTO_INCREMENT,
  USER_ID varchar(255) NOT NULL,
  CREATEDDATE datetime DEFAULT NULL,
  MODIFIEDDATE datetime DEFAULT NULL,
  ACTIVE tinyint(1) NOT NULL DEFAULT '0',
  TICKETID varchar(255) DEFAULT NULL,
  KEY NewIndex_1 (TOKEN_ID)
) ENGINE=InnoDB AUTO_INCREMENT=503834 DEFAULT CHARSET=utf8;

CREATE TABLE POSACTIONSACCESS( 
	ID VARCHAR(255), 
	ROLEID VARCHAR(255), 
	PRINTACCESS VARCHAR(1) DEFAULT 'N', 
	SETTLEACCESS VARCHAR(1) DEFAULT 'N',  
	CANCELACCESS VARCHAR(1) DEFAULT 'N', 
	DISCOUNTACCESS VARCHAR(1) DEFAULT 'N', 
	SPLITACCESS VARCHAR(1) DEFAULT 'N', 
	KOTACCESS VARCHAR(1) DEFAULT 'N', 
	MOVETABLEACCESS VARCHAR(1) DEFAULT 'N'
	)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE STAFFS( 
	ID VARCHAR(255), 
	SEARCHKEY VARCHAR(255) NOT NULL, 
	NAME VARCHAR(255)  NOT NULL, 
	PHONENO VARCHAR(255), 
	ISACTIVE VARCHAR(1) DEFAULT 'N',
	PRIMARY KEY (ID)
	)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE KODSTATUSMASTER (
 ID varchar(255) NOT NULL,
 NAME varchar(50) NOT NULL,
 COLORCODE varchar(50) ,
 SEQUENCENO INT (5),
 ISLASTSTATUS varchar(1) NOT NULL DEFAULT 'N',
 PRIMARY KEY (ID),
 UNIQUE (SEQUENCENO)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE KODSTATUSROLEACCESS (
 ID varchar(255) NOT NULL,
 KDSSTATUS_ID varchar(255) NOT NULL,
 ROLEID varchar(255) NOT NULL,
 PRIMARY KEY (ID),
 CONSTRAINT KODSTATUSROLEACCESS_FK_KODSTATUSMASTER FOREIGN KEY (KDSSTATUS_ID) REFERENCES KODSTATUSMASTER(ID),
 CONSTRAINT KODSTATUSROLEACCESS_FK_ROLE FOREIGN KEY (ROLEID) REFERENCES ROLES(ID)
 )ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE KDSROLESETTINGS (
  ID varchar(255) NOT NULL,
  ROLEID varchar(255) NOT NULL,
  VIEWMODE varchar(255) DEFAULT NULL,
  LISTVIEWROWS int(11),
  ORDERVIEWROWS int(11),
  ORDERVIEWCOLUMNS int(11),
  REFRESHTIMEMIN time ,
  REFRESHTIMEMAX time ,
  BUFFERTIME time ,
  CREATEDBY varchar(255) DEFAULT NULL,
  MODIFIEDBY varchar(255) DEFAULT NULL,
  CREATEDDATE datetime DEFAULT NULL,
  MODIFIEDDATE datetime DEFAULT NULL,
   HEIGHT INT(3),
  FONT INT(3),
   PRIMARY KEY (ID),
   UNIQUE(ROLEID),
   CONSTRAINT kdsrolesettings_fk_role FOREIGN KEY (ROLEID) REFERENCES ROLES(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PRODUCTIONAREAROLEMAP( 
ID VARCHAR(255),
ROLEID VARCHAR(255) NOT NULL,
PRODUCTIONAREATYPE VARCHAR(255),
PRIMARY KEY (ID),
CONSTRAINT PRODUCTIONAREAROLEMAP_FK_ROLE FOREIGN KEY (ROLEID) REFERENCES ROLES(ID),
CONSTRAINT PRODUCTIONAREAROLEMAP_FK_PRODUCTIONAREATYPE FOREIGN KEY (PRODUCTIONAREATYPE) REFERENCES PRODUCTIONAREATYPE(ID)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE MENU (
 ID varchar(255) NOT NULL,
 NAME varchar(255) NOT NULL,
 STARTDATE date NOT NULL,
 STARTTIME time NOT NULL,
 ENDDATE date NOT NULL,
 ENDTIME time NOT NULL,
 WEEKDAY varchar(1) DEFAULT 'N',
 WEEKENDS varchar(1) DEFAULT 'N',
 ALLDAY varchar(1) NOT NULL DEFAULT 'N',
 SUNDAY varchar(1) NOT NULL DEFAULT 'N',
 MONDAY varchar(1) NOT NULL DEFAULT 'N',
 TUESDAY varchar(1) NOT NULL DEFAULT 'N',
 WEDNESDAY varchar(1) NOT NULL DEFAULT 'N',
 THURSDAY varchar(1) NOT NULL DEFAULT 'N',
 FRIDAY varchar(1) NOT NULL DEFAULT 'N',
 SATURDAY varchar(1) NOT NULL DEFAULT 'N',
 ACTIVE varchar(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE MENUPRICELIST(
ID VARCHAR(255) NOT NULL,
MENUID VARCHAR(255) NOT NULL,
PRODUCTID VARCHAR(255)  NOT NULL,
PRICEBUY DOUBLE NOT NULL, 
PRICESELL DOUBLE NOT NULL,
MRP DOUBLE NOT NULL,
PRODUCTCAT VARCHAR(255) NOT NULL,
PRODUCTSEQUENCE int(2),
CATSEQUENCE int(4),
PRIMARY KEY (ID),
CONSTRAINT MENUPRICELIST_FK_MENU FOREIGN KEY (MENUID) REFERENCES MENU(ID),
CONSTRAINT MENUPRICELIST_FK_PRODUCT FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID),
CONSTRAINT MENUPRICELIST_FK_PRODUCTCAT FOREIGN KEY (PRODUCTCAT) REFERENCES CATEGORIES (ID))
ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE SERVEDTRANSACTION(  
ID varchar(255) NOT NULL,   
ORDERNUM int(11) DEFAULT NULL, 
TABLEID varchar(255) DEFAULT NULL,
ORDERITEM_ID varchar(255) NOT NULL,  
TXSTATUS VARCHAR(60) NOT NULL DEFAULT 'ADD',
KOTID int(20) NOT NULL,
PRODUCTNAME varchar(255) DEFAULT NULL,
MULTIPLY DOUBLE NOT NULL DEFAULT '1',         
PREPARATIONTIME varchar(255)  DEFAULT NULL,
KOTDATE DATETIME DEFAULT NULL,
KDSPREPARESTATUS VARCHAR(60) NOT NULL DEFAULT 'NEW',
INSTRUCTION varchar(255) DEFAULT NULL,
ADDONID VARCHAR(55) DEFAULT NULL,           
PRIMARYADDON int(1) NOT NULL,          
PRODUCTIONAREATYPE varchar(32) DEFAULT NULL,
STATION VARCHAR(60) DEFAULT NULL,
PREPARATIONSTATUS INT(1) DEFAULT NULL,
SERVEDBY VARCHAR(60) DEFAULT NULL,
SERVEDTIME DATETIME DEFAULT NULL,   
UPDATED datetime(3) DEFAULT NULL,
ISKDS int(1) DEFAULT NULL,      
PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE INSTRUCTION(  
ID varchar(255) NOT NULL,   
NAME varchar(255) DEFAULT NULL, 
CREATED DATETIME DEFAULT NULL,
UPDATED DATETIME DEFAULT NULL,      
PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE MOBILETYPEMASTERS (
  ID varchar(255) NOT NULL,
  MOBILETYPE varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


