/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sysfore.pos.accountingconfig;

import com.openbravo.basic.BasicException;
import com.openbravo.pos.customers.DataLogicCustomers;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.JPanelView;
import java.awt.Color;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;


/**
 *
 * @author raghevendra
 */
public class AccountingConfig extends javax.swing.JPanel implements JPanelView,BeanFactoryApp{
    //private DataLogicCustomers dlCustomers;
    private AccountingOperations accountingOP;
    private static volatile SecureRandom numberGenerator = null;
    private static final long MSB = 0x8000000000000000L;
    String accId=null;
    String id=null;
    boolean insertFlag = true;
    /**
     * Creates new form AccountingConfig
     */
    public AccountingConfig() {
        initComponents();
    }
      public void init(AppView app) throws BeanFactoryException{
          
          
          accountingOP=(AccountingOperations)app.getBean("com.sysfore.pos.accountingconfig.AccountingOperations");
          jASalesAccountinglabel.setBackground(Color.GRAY);
      
      }
      
      
      public static String genRandom32Hex() {
        SecureRandom ng = numberGenerator;
        if (ng == null) {
            numberGenerator = ng = new SecureRandom();
        }

        return Long.toHexString(MSB | ng.nextLong()) + Long.toHexString(MSB | ng.nextLong());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jASalesAccountinglabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jJournallabel = new javax.swing.JLabel();
        jCustomerlabel = new javax.swing.JLabel();
        jVendorlabel = new javax.swing.JLabel();
        jProduct = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JAdvanceAccount = new javax.swing.JTextField();
        jCustomerCredit = new javax.swing.JTextField();
        jProductCredit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jJournalCredit = new javax.swing.JTextField();
        jPurchaseDiscount = new javax.swing.JTextField();
        jproductDebit = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCustomerDebit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jReceivable = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jJournalDebit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpurchaseDebitTax = new javax.swing.JTextField();
        jLabeldiscount = new javax.swing.JLabel();
        jsalesCreditwithout = new javax.swing.JTextField();
        jcashDebit = new javax.swing.JTextField();
        jcardDebit = new javax.swing.JTextField();
        jchequeDebit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDiscountDebit = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jsalesCredit1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jService = new javax.swing.JTextField();
        credit = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jpurchaseDebit = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPurchaseCredit1 = new javax.swing.JTextField();
        jRoundoff = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.disabledForeground")));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jASalesAccountinglabel.setBackground(new java.awt.Color(47, 28, 28));
        jASalesAccountinglabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        jASalesAccountinglabel.setText("   Sales Accounting ");
        jPanel1.add(jASalesAccountinglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 670, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel2.setText("Sales Credit");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 104, 20));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel3.setText("Cash Debit");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 89, 20));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel4.setText("Card Debit");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 79, 20));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel5.setText("Cheque Debit");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 104, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel16.setText("   Purchase Accounting");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 256, 670, -1));

        jJournallabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        jJournallabel.setText("   Journal");
        jPanel1.add(jJournallabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 670, 30));

        jCustomerlabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        jCustomerlabel.setText("   Customer");
        jPanel1.add(jCustomerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 405, 670, 20));

        jVendorlabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        jVendorlabel.setText("   Vendor");
        jPanel1.add(jVendorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 670, 10));

        jProduct.setFont(new java.awt.Font("Tahoma", 1, 11));
        jProduct.setText("   Product");
        jPanel1.add(jProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 670, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 80, 30));

        JAdvanceAccount.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(JAdvanceAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 160, -1));

        jCustomerCredit.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jCustomerCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 160, -1));

        jProductCredit.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jProductCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 160, -1));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel12.setText("Debit");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 100, 20));

        jJournalCredit.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jJournalCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 160, -1));

        jPurchaseDiscount.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jPurchaseDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 160, -1));

        jproductDebit.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jproductDebit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 160, -1));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel13.setText("Credit");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 90, 20));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel14.setText("Debit");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 50, 20));

        jCustomerDebit.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jCustomerDebit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 160, -1));

        jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel15.setText("Credit");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 50, 20));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel10.setText("Receivable");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 110, 30));

        jReceivable.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jReceivable, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 160, -1));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel11.setText("Advance Account");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 90, 20));

        jJournalDebit.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jJournalDebit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 160, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel8.setText("Debit");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 110, 60));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel9.setText("Credit");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 90, 20));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel6.setText("Debit");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, 20));

        jpurchaseDebitTax.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jpurchaseDebitTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 160, -1));

        jLabeldiscount.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabeldiscount.setText("Discount");
        jPanel1.add(jLabeldiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 90, 20));

        jsalesCreditwithout.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jsalesCreditwithout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalesCreditwithoutActionPerformed(evt);
            }
        });
        jPanel1.add(jsalesCreditwithout, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 160, -1));

        jcashDebit.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jcashDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcashDebitActionPerformed(evt);
            }
        });
        jPanel1.add(jcashDebit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 160, -1));

        jcardDebit.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jcardDebit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 160, -1));

        jchequeDebit.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jchequeDebit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 160, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel1.setText("Discount Debit");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, 20));

        jDiscountDebit.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jDiscountDebit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 160, -1));

        jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel17.setText("Sales Credit with Tax");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 20));

        jsalesCredit1.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jsalesCredit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalesCredit1ActionPerformed(evt);
            }
        });
        jPanel1.add(jsalesCredit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 160, -1));

        jLabel19.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        jLabel19.setText("RoundOff Account");
        jLabel19.setFocusCycleRoot(true);
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 120, 20));

        jService.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jServiceActionPerformed(evt);
            }
        });
        jPanel1.add(jService, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 160, -1));

        credit.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 160, -1));

        jLabel20.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel20.setText("Credit");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 20));

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 271, 668, 0));

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, javax.swing.UIManager.getDefaults().getColor("Button.disabledForeground")));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 338, 668, 0));

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 345, 668, 0));

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 347, 668, 20));

        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 271, 668, 3));

        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 341, 668, 0));

        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 396, 668, 30));

        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 482, 668, 3));

        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 537, 668, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));
        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 24, 668, 3));

        jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel18.setText("Purchase Debit with Tax");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 20));

        jpurchaseDebit.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jpurchaseDebit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 160, -1));

        jLabel21.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel21.setText("Credit");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 90, 20));

        jPurchaseCredit1.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jPanel1.add(jPurchaseCredit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 160, -1));

        jRoundoff.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jRoundoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRoundoffActionPerformed(evt);
            }
        });
        jPanel1.add(jRoundoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 160, -1));

        jLabel22.setFont(new java.awt.Font("Ubuntu", 0, 11));
        jLabel22.setText("Service Tax");
        jLabel22.setFocusCycleRoot(true);
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 70, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 670, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void jsalesCreditwithoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalesCreditwithoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsalesCreditwithoutActionPerformed

    private void jcashDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcashDebitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcashDebitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        String salesCredit=jsalesCredit1.getText();
        String cashDebit=jcashDebit.getText();
        String cardDebit=jcardDebit.getText();        
        String chequeDebit=jchequeDebit.getText();
        String purDebit=jpurchaseDebitTax.getText();
        String purDiscount=jPurchaseDiscount.getText();
        String purCredit=jPurchaseDiscount.getText();
        String jourDebit=jJournalDebit.getText();
        String jourCrebit=jJournalCredit.getText();
        String venDebit= jReceivable.getText();
        String venCrebit=JAdvanceAccount.getText();
        String cusDebit=jCustomerDebit.getText();
        String cusCrebit=jCustomerCredit.getText();                
        String proDebit=jproductDebit.getText();
        String proCrebit=jProductCredit.getText();
        String discountDebit=jDiscountDebit.getText();
        String nontaxcredit=jsalesCreditwithout.getText();;
        String servicetax=jService.getText(); 
        String creditval=credit.getText();
        String purDebitNonTax=jpurchaseDebit.getText();
        String purchaseDiscount=jPurchaseDiscount.getText();
        String roundOff=jRoundoff.getText();
        
        if(accId==null)
        id=genRandom32Hex();
        else{
        id=accId;
        insertFlag = false;
        }
        AccountingPojo ap=new AccountingPojo();
        ap.setId(id);
        ap.setSalesCredit(salesCredit);
        ap.setCashDebit(cashDebit);
        ap.setCardDebit(cardDebit);
        ap.setChequeDebit(chequeDebit);
        ap.setPurDebit(purDebit);
        ap.setPurCredit(purCredit);
        ap.setJourDebit(jourDebit);
        ap.setJourCrebit(jourCrebit);
        ap.setVenDebit(venDebit);
        ap.setVenCrebit(venCrebit);
        ap.setCusDebit(cusDebit);
        ap.setCusCrebit(cusCrebit);
        ap.setProDebit(proDebit);
        ap.setProCrebit(proCrebit);
        ap.setDiscountDebit(discountDebit);
        ap.setNonTaxCredit(nontaxcredit);
        ap.setServiceTaxCredit(servicetax);
        ap.setCredit(creditval);
        ap.setPurchaseNonTax(purDebitNonTax);
        ap.setPurchaseDiscount(purchaseDiscount);
        ap.setRoundOff(roundOff);
       
        try {
            if(insertFlag) {
                accountingOP.insertAccountingValues(ap);
                accountingDetails();
            }else {
                accountingOP.updateAccounting(ap);
                accountingDetails();
            }
          // dlCustomers.getAccountingValues();
        } catch (BasicException ex) {
            Logger.getLogger(AccountingConfig.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jsalesCredit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalesCredit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsalesCredit1ActionPerformed

    private void jServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jServiceActionPerformed

    private void jRoundoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRoundoffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRoundoffActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JAdvanceAccount;
    private javax.swing.JTextField credit;
    private javax.swing.JLabel jASalesAccountinglabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCustomerCredit;
    private javax.swing.JTextField jCustomerDebit;
    private javax.swing.JLabel jCustomerlabel;
    private javax.swing.JTextField jDiscountDebit;
    private javax.swing.JTextField jJournalCredit;
    private javax.swing.JTextField jJournalDebit;
    private javax.swing.JLabel jJournallabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabeldiscount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jProduct;
    private javax.swing.JTextField jProductCredit;
    private javax.swing.JTextField jPurchaseCredit1;
    private javax.swing.JTextField jPurchaseDiscount;
    private javax.swing.JTextField jReceivable;
    private javax.swing.JTextField jRoundoff;
    private javax.swing.JTextField jService;
    private javax.swing.JLabel jVendorlabel;
    private javax.swing.JTextField jcardDebit;
    private javax.swing.JTextField jcashDebit;
    private javax.swing.JTextField jchequeDebit;
    private javax.swing.JTextField jproductDebit;
    private javax.swing.JTextField jpurchaseDebit;
    private javax.swing.JTextField jpurchaseDebitTax;
    private javax.swing.JTextField jsalesCredit1;
    private javax.swing.JTextField jsalesCreditwithout;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
          return AppLocal.getIntString("Menu.accountConfig");
        //return AppLocal.getIntString("Default Accounting Configuration");
    }

    @Override
    public void activate() throws BasicException {
        insertFlag = true;
        accountingDetails();
      
    }

    @Override
    public boolean deactivate() {
         return true;
    }

    @Override
    public JComponent getComponent() {
         return this;
    }

    @Override
    public Object getBean() {
         return this;
    }
    
    
   public void accountingDetails()
   {
       
       try {
         ArrayList<AccountingPojo> list=accountingOP.getAccountingValues();
         if(list!=null && list.size()!=0 ){
                 accId=list.get(0).getId().toString(); 
                 jsalesCredit1.setText(list.get(0).getSalesCredit());
                 jsalesCreditwithout.setText(list.get(0).getNonTaxCredit());
                 jcashDebit.setText(list.get(0).getCashDebit());
                 jcardDebit.setText(list.get(0).getCardDebit());
                 jchequeDebit.setText(list.get(0).getChequeDebit());
                 jpurchaseDebitTax.setText(list.get(0).getPurDebit());
                 jPurchaseDiscount.setText(list.get(0).getPurCredit());
                 jJournalDebit.setText(list.get(0).getJourDebit());
                 jJournalCredit.setText(list.get(0).getJourCrebit());
                 jReceivable.setText(list.get(0).getVenDebit());
                 JAdvanceAccount.setText(list.get(0).getVenCrebit());
                 jCustomerDebit.setText(list.get(0).getCusDebit());
                 jCustomerCredit.setText(list.get(0).getCusCrebit());
                 jproductDebit.setText(list.get(0).getProDebit());
                 jProductCredit.setText(list.get(0).getProCrebit());
                 jDiscountDebit.setText(list.get(0).getDiscountDebit());
                 credit.setText(list.get(0).getCredit());
                 jService.setText(list.get(0).getServiceTaxCredit());
                 jpurchaseDebit.setText(list.get(0).getPurchaseNonTax());
                 jPurchaseDiscount.setText(list.get(0).getPurchaseDiscount());
                 jRoundoff.setText(list.get(0).getRoundOff());
         }
                 
                 
                 
           
        } catch (BasicException ex) {
            Logger.getLogger(AccountingConfig.class.getName()).log(Level.SEVERE, null, ex);
        }
        
   
   }
}
